In [1]:
!nvidia-smi

Sat Aug 29 11:28:15 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!apt-get update -qq
!apt-get install -y zstd pciutils
!pip -q install pandas openpyxl requests

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpci3 pci.ids
The following NEW packages will be installed:
  libpci3 pci.ids pciutils zstd
0 upgraded, 4 newly installed, 0 to remove and 77 not upgraded.
Need to get 946 kB of archives.
After this operation, 3,276 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pci.ids all 0.0~2022.01.22-1ubuntu0.1 [251 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpci3 amd64 1:3.7.0-6 [28.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 pciutils amd64 1:3.7.0-6 [63.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 946 kB in 2s (468 kB/s)
Selecting previously unselected package pci.ids.
(Reading database ... 122579 files and directories currently installed.)
Preparing to unpack .../pci.ids_0.0~2022.01.22-1ubuntu0.1_all.deb ...
Unpacking pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Selecting previously unselected package libpci3:amd64.
Preparing to unpack .../libpci3_1%3a3.7.0-6_amd64.deb ...
Unpacking libpci3:amd64 (1:3.7.0-6) ...
Selecting previously unselected package pciutils.
Preparing to unpack .../pciutils_1%3a3.7.0-6_amd64.deb ...
Unpacking pciutils (1:3.7.0-6) ...
Selecting previously unselected package zstd.
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Setting up libpci3:amd64 (1:3.7.0-6) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Setting up pciutils (1:3.7.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

In [4]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
>>> NVIDIA GPU installed.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [5]:
import subprocess
import time
import requests

ollama_process = subprocess.Popen(
    ["ollama", "serve"],
    stdout=open("/content/ollama.log", "w"),
    stderr=subprocess.STDOUT
)

time.sleep(5)

response = requests.get(
    "http://127.0.0.1:11434/api/tags"
)

print("Ollama status:", response.status_code)

Ollama status: 200

In [7]:
!ollama pull gemma3:4b

In [8]:
from pathlib import Path
import pandas as pd

INPUT_FILE = Path(
    "/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_LLM_Benchmark.xlsx"
)

RESULT_FILE = Path(
    "/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Gemma3_Results.xlsx"
)

print("Input exists:", INPUT_FILE.exists())

df = pd.read_excel(
    INPUT_FILE,
    sheet_name="Benchmark"
)

print("Number of records:", len(df))

Input exists: True
Number of records: 500

In [9]:
df["gemma_output"] = ""
df["gemma_raw"] = ""
df["gemma_status"] = ""
df["gemma_runtime_sec"] = ""

df.to_excel(
    RESULT_FILE,
    index=False
)

print("Created:")
print(RESULT_FILE)

Created:
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Gemma3_Results.xlsx

In [11]:
import json
import time
import requests

MODEL = "gemma3:4b"

URL = "http://127.0.0.1:11434/api/chat"


SYSTEM_MESSAGE = """
You are a biomedical information extraction system.
Follow the user's extraction instructions exactly.
Return only the requested JSON output.
""".strip()


EXTRACTION_TEMPLATE = """
Extract ALL diseases, disorders, syndromes, symptoms, or clinical conditions
for which the drug is explicitly indicated in the following
Indications and Usage text.

Rules:

1. Read the entire supplied text.
2. Include every explicitly stated clinical indication.
3. Include symptoms or clinical conditions when explicitly indicated
   for treatment, prevention, management, or relief.
4. Preserve clinically meaningful disease subtypes and modifiers.
5. Use wording from the supplied text as closely as possible.
6. Do not intentionally normalize or generalize disease names.
7. Do not infer conditions that are not explicitly supported by the text.
8. Exclude conditions explicitly stated as NOT indicated or NOT recommended.
9. Exclude causative organisms when they merely describe the cause of infection.
10. Exclude mechanisms, procedures, dosing information,
    treatment regimens, and patient demographics.
11. Remove duplicate clinical conditions.

Return ONLY valid JSON:

{{"diseases":["condition 1","condition 2"]}}

If there are genuinely no indications:

{{"diseases":[]}}

INDICATIONS AND USAGE:

{indication_text}
""".strip()

In [12]:
def parse_output(raw_output):

    raw_output = str(raw_output).strip()

    try:

        parsed = json.loads(
            raw_output
        )

    except json.JSONDecodeError:

        start = raw_output.find("{")
        end = raw_output.rfind("}")

        if start == -1 or end == -1:

            raise ValueError(
                "No JSON object found in model response."
            )

        parsed = json.loads(
            raw_output[start:end + 1]
        )


    if "diseases" not in parsed:

        raise ValueError(
            "JSON does not contain 'diseases'."
        )


    diseases = parsed["diseases"]


    if not isinstance(diseases, list):

        raise ValueError(
            "'diseases' must be a list."
        )


    cleaned = []
    seen = set()


    for disease in diseases:

        if not isinstance(disease, str):
            continue

        disease = disease.strip()

        if not disease:
            continue

        key = disease.lower()

        if key not in seen:

            seen.add(key)
            cleaned.append(disease)


    return cleaned

In [13]:
def extract_gemma(indication_text):

    user_message = EXTRACTION_TEMPLATE.format(
        indication_text=indication_text
    )

    payload = {

        "model": MODEL,

        "messages": [

            {
                "role": "system",
                "content": SYSTEM_MESSAGE
            },

            {
                "role": "user",
                "content": user_message
            }
        ],

        "stream": False,

        "options": {

            "temperature": 0.1,

            "num_ctx": 4096,

            "num_predict": 1000
        }
    }


    start_time = time.time()


    response = requests.post(
        URL,
        json=payload,
        timeout=240
    )

    response.raise_for_status()


    raw = (
        response.json()
        ["message"]
        ["content"]
    )


    runtime = round(
        time.time() - start_time,
        2
    )


    # Keep raw response even if JSON parsing fails
    try:

        diseases = parse_output(raw)

        status = (
            "OK"
            if diseases
            else "OK_EMPTY"
        )

    except Exception:

        diseases = []
        status = "FORMAT_FAILED"


    return diseases, raw, runtime, status

In [14]:
test_text = """
Metoprolol is indicated for the treatment of hypertension and angina pectoris.
"""

diseases, raw, runtime, status = extract_gemma(
    test_text
)

print("RAW:")
print(raw)

print()

print("PARSED:")
print(diseases)

print()

print("STATUS:")
print(status)

print()

print("Runtime:", runtime)

RAW:
```json
{"diseases":["hypertension","angina pectoris"]}
```

PARSED:
['hypertension', 'angina pectoris']

STATUS:
OK

Runtime: 97.72

In [15]:
for i in range(5):

    record_id = df.loc[i, "record_id"]

    indication_text = str(
        df.loc[i, "indication_text"]
    )


    print()
    print("=" * 70)
    print(f"RECORD {i + 1}/5")
    print("Record ID:", record_id)

    print()
    print("EXPERT GOLD:")
    print(
        df.loc[i, "gold_expert_mentions"]
    )


    try:

        diseases, raw, runtime, status = extract_gemma(
            indication_text
        )


        df.at[
            i,
            "gemma_output"
        ] = json.dumps(
            diseases,
            ensure_ascii=False
        )


        df.at[
            i,
            "gemma_raw"
        ] = raw


        df.at[
            i,
            "gemma_status"
        ] = status


        df.at[
            i,
            "gemma_runtime_sec"
        ] = runtime


        print()
        print("GEMMA3 OUTPUT:")
        print(diseases)

        print(
            "Status:",
            status
        )

        print(
            "Runtime:",
            runtime,
            "seconds"
        )


    except Exception as e:

        df.at[
            i,
            "gemma_status"
        ] = "FAILED"

        df.at[
            i,
            "gemma_raw"
        ] = str(e)

        print(
            "TECHNICAL ERROR:",
            e
        )


df.to_excel(
    RESULT_FILE,
    index=False
)

print()
print("Saved:")
print(RESULT_FILE)

======================================================================
RECORD 1/5
Record ID: 10004

EXPERT GOLD:
Erosive Esophagitis; Gastroesophageal Reflux Disease; GERD; Zollinger Ellison Syndrome

GEMMA3 OUTPUT:
['Erosive Esophagitis', 'Gastroesophageal Reflux Disease', 'GERD', 'Zollinger Ellison Syndrome']
Status: OK
Runtime: 0.99 seconds

======================================================================
RECORD 2/5
Record ID: 10008

EXPERT GOLD:
Anxiety Disorders; anxiety disorder; Anxiety; Anxiety associated with depression; Panic Disorder; agoraphobia

GEMMA3 OUTPUT:
['Anxiety Disorders', 'Generalized anxiety disorder', 'Anxiety', 'Panic Disorder', 'Agoraphobia', 'Depression']
Status: OK
Runtime: 1.16 seconds

======================================================================
RECORD 3/5
Record ID: 10012

EXPERT GOLD:
ventricular fibrillation; ventricular tachycardia; VT; VF

GEMMA3 OUTPUT:
['ventricular fibrillation', 'ventricular tachycardia']
Status: OK
Runtime: 0.78 seconds

======================================================================
RECORD 4/5
Record ID: 10016

EXPERT GOLD:
dermatoses; plaque type psoriasis

GEMMA3 OUTPUT:
['corticosteroid responsive dermatoses', 'plaque type psoriasis', 'adrenal suppression']
Status: OK
Runtime: 0.68 seconds

======================================================================
RECORD 5/5
Record ID: 10017

EXPERT GOLD:
acute, painful

GEMMA3 OUTPUT:
['acute, painful musculoskeletal conditions']
Status: OK
Runtime: 0.46 seconds

Saved:
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Gemma3_Results.xlsx

In [16]:
display(
    df[
        [
            "record_id",
            "gold_expert_mentions",
            "gemma_output",
            "gemma_status",
            "gemma_runtime_sec"
        ]
    ].head(5)
)

,record_id,gold_expert_mentions,gemma_output,gemma_status,gemma_runtime_sec
0,10004,Erosive Esophagitis; Gastroesophageal Reflux D...,"[""Erosive Esophagitis"", ""Gastroesophageal Refl...",OK,0.99
1,10008,Anxiety Disorders; anxiety disorder; Anxiety; ...,"[""Anxiety Disorders"", ""Generalized anxiety dis...",OK,1.16
2,10012,ventricular fibrillation; ventricular tachycar...,"[""ventricular fibrillation"", ""ventricular tach...",OK,0.78
3,10016,dermatoses; plaque type psoriasis,"[""corticosteroid responsive dermatoses"", ""plaq...",OK,0.68
4,10017,"acute, painful","[""acute, painful musculoskeletal conditions""]",OK,0.46

In [18]:
def run_all_gemma():

    total = len(df)


    for i in range(total):

        record_id = df.loc[
            i,
            "record_id"
        ]


        current_status = str(
            df.at[
                i,
                "gemma_status"
            ]
        ).strip()


        # Skip completed experimental results
        if current_status in [
            "OK",
            "OK_EMPTY",
            "FORMAT_FAILED"
        ]:

            print(
                f"[{i + 1}/{total}] "
                f"Record {record_id} - already completed"
            )

            continue


        indication_text = str(
            df.loc[
                i,
                "indication_text"
            ]
        )


        print()
        print("=" * 70)

        print(
            f"[{i + 1}/{total}] "
            f"Record ID: {record_id}"
        )


        try:

            diseases, raw, runtime, status = extract_gemma(
                indication_text
            )


            df.at[
                i,
                "gemma_output"
            ] = json.dumps(
                diseases,
                ensure_ascii=False
            )


            df.at[
                i,
                "gemma_raw"
            ] = raw


            df.at[
                i,
                "gemma_status"
            ] = status


            df.at[
                i,
                "gemma_runtime_sec"
            ] = runtime


            print(
                "Output:",
                diseases
            )

            print(
                "Status:",
                status
            )

            print(
                "Runtime:",
                runtime,
                "seconds"
            )


        except Exception as e:

            df.at[
                i,
                "gemma_status"
            ] = "FAILED"

            df.at[
                i,
                "gemma_raw"
            ] = str(e)


            print(
                "TECHNICAL ERROR:",
                e
            )


        # Checkpoint every 20 records
        if (
            (i + 1) % 20 == 0
            or
            i == total - 1
        ):

            df.to_excel(
                RESULT_FILE,
                index=False
            )

            print(
                ">>> CHECKPOINT SAVED TO GOOGLE DRIVE"
            )


    # Final save
    df.to_excel(
        RESULT_FILE,
        index=False
    )


    print()
    print("=" * 70)
    print("GEMMA3 FINISHED")
    print("=" * 70)

    print(
        "Results saved to:"
    )

    print(
        RESULT_FILE
    )

In [19]:
run_all_gemma()

[1/500] Record 10004 - already completed
[2/500] Record 10008 - already completed
[3/500] Record 10012 - already completed
[4/500] Record 10016 - already completed
[5/500] Record 10017 - already completed

======================================================================
[6/500] Record ID: 1001
Output: ['Hypertension', 'Angina Pectoris', 'Myocardial Infarction']
Status: OK
Runtime: 0.77 seconds

======================================================================
[7/500] Record ID: 10140
Output: ['major depressive disorder', 'generalized seizures', 'Major Depression']
Status: OK
Runtime: 0.69 seconds

======================================================================
[8/500] Record ID: 10146
Output: ['insomnia']
Status: OK
Runtime: 0.53 seconds

======================================================================
[9/500] Record ID: 10153
Output: ['anxiety', 'tension', 'psychoneurosis', 'organic disease states', 'pruritus', 'allergic conditions', 'chronic urticaria', 'atopic dermatoses', 'contact dermatoses', 'histamine mediated pruritus']
Status: OK
Runtime: 1.27 seconds

======================================================================
[10/500] Record ID: 10157
Output: ["Parkinson's disease", "idiopathic Parkinson's disease"]
Status: OK
Runtime: 0.75 seconds

======================================================================
[11/500] Record ID: 10173
Output: ['partial onset seizures', 'myoclonic seizures', 'juvenile myoclonic epilepsy', 'primary generalized tonic clonic seizures', 'idiopathic generalized epilepsy']
Status: OK
Runtime: 0.91 seconds

======================================================================
[12/500] Record ID: 1024
Output: ['head lice infestations']
Status: OK
Runtime: 0.45 seconds

======================================================================
[13/500] Record ID: 10263
Output: ['LOWER RESPIRATORY TRACT INFECTIONS', 'ACUTE BACTERIAL OTITIS MEDIA', 'SKIN AND SKIN STRUCTURE INFECTIONS', 'URINARY TRACT INFECTIONS', 'UNCOMPLICATED GONORRHEA', 'PHARYNGAL GONORRHEA', 'PELVIC INFLAMMATORY DISEASE', 'BACTERIAL SEPTICEMIA', 'BONE AND JOINT INFECTIONS', 'INTRA ABDOMINAL INFECTIONS', 'MENINGITIS', 'SURGICAL PROPHYLAXIS']
Status: OK
Runtime: 3.9 seconds

======================================================================
[14/500] Record ID: 10268
Output: ['Essential hypertension']
Status: OK
Runtime: 0.71 seconds

======================================================================
[15/500] Record ID: 10295
Output: ['megaloblastic anemias', 'tropical or nontropical sprue', 'anemias of nutritional origin', 'pregnancy', 'infancy', 'childhood']
Status: OK
Runtime: 0.93 seconds

======================================================================
[16/500] Record ID: 10303
Output: ['benign prostatic hyperplasia', 'prostate']
Status: OK
Runtime: 0.55 seconds

======================================================================
[17/500] Record ID: 10311
Output: ['venous thrombosis', 'pulmonary embolism', 'atrial fibrillation', 'cardiac valve replacement', 'myocardial infarction', 'stroke', 'systemic embolization']
Status: OK
Runtime: 0.97 seconds

======================================================================
[18/500] Record ID: 10312
Output: ['type 2 diabetes mellitus']
Status: OK
Runtime: 0.52 seconds

======================================================================
[19/500] Record ID: 10316
Output: ['Benign Prostatic Hyperplasia', 'BPH', 'urinary outflow obstruction', 'obstructive symptoms', 'hesitation', 'intermittency', 'dribbling', 'weak urinary stream', 'incomplete emptying of the bladder', 'irritative symptoms', 'nocturia', 'daytime frequency', 'urgency', 'burning', 'Hypertension', 'Hypertensive']
Status: OK
Runtime: 1.76 seconds

======================================================================
[20/500] Record ID: 10318
Output: ['corticosteroid responsive dermatoses', 'plaque type psoriasis']
Status: OK
Runtime: 0.85 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[21/500] Record ID: 10319
Output: ['nausea', 'vomiting', 'postoperative nausea and/or vomiting']
Status: OK
Runtime: 0.84 seconds

======================================================================
[22/500] Record ID: 10320
Output: ['intermittent claudication']
Status: OK
Runtime: 0.51 seconds

======================================================================
[23/500] Record ID: 10322
Output: ['hyperkalemia']
Status: OK
Runtime: 0.48 seconds

======================================================================
[24/500] Record ID: 10445
Output: ['cough']
Status: OK
Runtime: 0.45 seconds

======================================================================
[25/500] Record ID: 11458
Output: ['Major Depressive Disorder', 'Seasonal Affective Disorder']
Status: OK
Runtime: 1.01 seconds

======================================================================
[26/500] Record ID: 3022
Output: ['asthma']
Status: OK
Runtime: 0.56 seconds

======================================================================
[27/500] Record ID: 3533
Output: ['nausea', 'vomiting', 'motion sickness', 'anesthesia', 'surgery']
Status: OK
Runtime: 0.58 seconds

======================================================================
[28/500] Record ID: 3750
Output: ['Schizophrenia']
Status: OK
Runtime: 0.43 seconds

======================================================================
[29/500] Record ID: 4288
Output: ['pulmonary arterial hypertension', 'NYHA Functional Class II', 'NYHA Functional Class III', 'primary pulmonary hypertension', 'pulmonary hypertension associated with connective tissue disease']
Status: OK
Runtime: 0.98 seconds

======================================================================
[30/500] Record ID: 4292
Output: ['renal homotransplantation', 'Rheumatoid Arthritis', 'RA']
Status: OK
Runtime: 0.67 seconds

======================================================================
[31/500] Record ID: 4346
Output: ['gestational choriocarcinoma', 'chorioadenoma destruens', 'hydatidiform mole', 'acute lymphocytic leukemia', 'meningeal leukemia', 'breast cancer', 'epidermoid cancers of the head and neck', 'advanced mycosis fungoides', 'cutaneous T cell lymphoma', 'lung cancer', 'non Hodgkin s lymphomas', 'non metastatic osteosarcoma', 'psoriasis', 'Rheumatoid Arthritis', 'Juvenile Rheumatoid Arthritis']
Status: OK
Runtime: 2.31 seconds

======================================================================
[32/500] Record ID: 4498
Output: ['overactive bladder', 'urge urinary incontinence', 'urgency', 'frequency']
Status: OK
Runtime: 0.77 seconds

======================================================================
[33/500] Record ID: 4706
Output: ['bronchospasm', 'reversible obstructive airway disease']
Status: OK
Runtime: 0.52 seconds

======================================================================
[34/500] Record ID: 490
Output: ['Attention Deficit Disorders', 'Narcolepsy', 'Hyperkinetic Child Syndrome', 'Minimal Brain Damage', 'Minimal Cerebral Dysfunction', 'Minor Cerebral Dysfunction', 'central nervous system dysfunction', 'psychosis']
Status: OK
Runtime: 1.25 seconds

======================================================================
[35/500] Record ID: 4976
Output: ['primary hypogonadism', 'Klinefelter Syndrome', 'hypogonadotropic hypogonadism']
Status: OK
Runtime: 0.91 seconds

======================================================================
[36/500] Record ID: 558
Output: ['hypertension']
Status: OK
Runtime: 0.35 seconds

======================================================================
[37/500] Record ID: 5610
Output: ['hypertension', 'angina']
Status: OK
Runtime: 0.43 seconds

======================================================================
[38/500] Record ID: 6071
Output: ['Restless Legs Syndrome', 'Postherpetic Neuralgia']
Status: OK
Runtime: 0.59 seconds

======================================================================
[39/500] Record ID: 6412
Output: ['moderate to severe pain', 'opioid addiction']
Status: OK
Runtime: 0.76 seconds

======================================================================
[40/500] Record ID: 10
Output: ['hypertension']
Status: OK
Runtime: 0.39 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[41/500] Record ID: 1000
Output: ['Rocky mountain spotted fever', 'typhus fever', 'typhus group', 'Q fever', 'rickettsialpox', 'tick fevers', 'Mycoplasma pneumoniae', 'Lymphogranuloma venereum', 'Psittacosis', 'trachoma', 'inclusion conjunctivitis', 'uncomplicated urethral infections', 'endocervical infections', 'rectal infections', 'nongonococcal urethritis', 'relapsing fever', 'Chancroid', 'Plague', 'Tularemia', 'Cholera', 'Campylobacter fetus infections', 'Brucellosis', 'Bartonellosis', 'Granuloma inguinale', 'Respiratory tract infections', 'Escherichia coli', 'Enterobacter aerogenes', 'Shigella species', 'Acinetobacter species', 'Haemophilus influenzae', 'Klebsiella species', 'Streptococcus pneumoniae', 'Staphylococcus aureus', 'Anthrax', 'staphylococcal infections', 'gonorrhea', 'syphilis', 'Yaws', 'Listeriosis', "Vincent's infection", 'Actinomycosis', 'Clostridium species', 'acute intestinal amebiasis', 'severe acne']
Status: OK
Runtime: 5.51 seconds

======================================================================
[42/500] Record ID: 10000
Output: ['depression']
Status: OK
Runtime: 0.85 seconds

======================================================================
[43/500] Record ID: 10003
Output: ['Epilepsy', 'Partial seizures with complex symptomatology', 'Generalized tonic clonic seizures', 'Mixed seizure patterns', 'Absence seizures', 'Trigeminal Neuralgia', 'Glossopharyngeal neuralgia']
Status: OK
Runtime: 1.4 seconds

======================================================================
[44/500] Record ID: 10021
Output: ['Left Ventricular Dysfunction', 'Myocardial Infarction', 'Hypertension', 'Symptomatic heart failure']
Status: OK
Runtime: 0.95 seconds

======================================================================
[45/500] Record ID: 10023
Output: ['rosacea', 'inflammatory lesions of rosacea']
Status: OK
Runtime: 0.69 seconds

======================================================================
[46/500] Record ID: 10029
Output: []
Status: FORMAT_FAILED
Runtime: 2.94 seconds

======================================================================
[47/500] Record ID: 10036
Output: ["Parkinson's Disease", 'Restless Legs Syndrome']
Status: OK
Runtime: 0.99 seconds

======================================================================
[48/500] Record ID: 10041
Output: ['type 2 diabetes mellitus']
Status: OK
Runtime: 0.6 seconds

======================================================================
[49/500] Record ID: 10043
Output: ['allergic reactions', 'anaphylaxis', 'allergic conditions', 'motion sickness', 'postoperative pain', 'nausea', 'vomiting', 'objection (during labor)']
Status: OK
Runtime: 1.3 seconds

======================================================================
[50/500] Record ID: 10048
Output: ['depression', 'endogenous depressions']
Status: OK
Runtime: 0.59 seconds

======================================================================
[51/500] Record ID: 1005
Output: ['asthma', 'emphysema', 'chronic bronchitis']
Status: OK
Runtime: 0.65 seconds

======================================================================
[52/500] Record ID: 10054
Output: ['hypertension']
Status: OK
Runtime: 0.5 seconds

======================================================================
[53/500] Record ID: 10059
Output: ['Hypothyroidism', 'subacute thyroiditis', 'congenital hypothyroidism', 'primary hypothyroidism', 'secondary hypothyroidism', 'tertiary hypothyroidism', 'subclinical hypothyroidism', 'euthyroid goiters', 'thyroid nodules', "Hashimoto's thyroiditis", 'multinodular goiter', 'thyrotropin dependent well differentiated thyroid cancer']
Status: OK
Runtime: 2.16 seconds

======================================================================
[54/500] Record ID: 1006
Output: ['type 2 diabetes mellitus']
Status: OK
Runtime: 0.73 seconds

======================================================================
[55/500] Record ID: 10072
Output: ['Attention Deficit Hyperactivity Disorder', 'ADHD', 'psychosis']
Status: OK
Runtime: 1.12 seconds

======================================================================
[56/500] Record ID: 10073
Output: ['muscle spasm', 'pain', 'tenderness', 'limitation of motion', 'restriction in activities of daily living', 'musculoskeletal conditions']
Status: OK
Runtime: 1.36 seconds

======================================================================
[57/500] Record ID: 10082
Output: ['pneumonia', 'acute bacterial exacerbations of chronic obstructive pulmonary disease', 'acute bacterial sinusitis', 'community acquired pneumonia', 'pharyngitis tonsillitis', 'urethritis', 'cervicitis', 'genital ulcer disease', 'chancroid', 'syphilis', 'uncomplicated skin and skin structure infections', 'abscesses', 'acute otitis media', 'immunodeficiency', 'functional asplenia']
Status: OK
Runtime: 4.31 seconds

======================================================================
[58/500] Record ID: 10084
Output: ['Psychoneurotic patients with Depression', 'anxiety', 'Depression', 'involutional depression', 'manic depressive disorders', 'somatic symptoms', 'sleep disturbances', 'guilt', 'fear', 'apprehension', 'worry']
Status: OK
Runtime: 1.87 seconds

======================================================================
[59/500] Record ID: 10087
Output: ['Hypertension', 'Coronary Artery Disease', 'Chronic Stable Angina', 'Vasospastic Angina', 'Angina']
Status: OK
Runtime: 1.05 seconds

======================================================================
[60/500] Record ID: 1009
Output: ['Hypertension', 'Left Ventricular Hypertrophy', 'Stroke', 'Diabetic nephropathy', 'Nephropathy', 'Type 2 Diabetes', 'End stage renal disease']
Status: OK
Runtime: 1.25 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[61/500] Record ID: 10090
Output: ['acute pain', 'postoperative pain', 'breakthrough pain', 'opioid use']
Status: OK
Runtime: 0.98 seconds

======================================================================
[62/500] Record ID: 10091
Output: ['primary hypogonadism', 'testicular failure', 'cryptorchidism', 'bilateral torsion', 'orchitis', 'vanishing testis syndrome', 'orchidectomy', 'hypogonadotropic hypogonadism', 'idiopathic gonadotropin or LHRH deficiency', 'pituitary hypothalamic injury']
Status: OK
Runtime: 1.63 seconds

======================================================================
[63/500] Record ID: 10093
Output: ['very high elevations of serum triglyceride levels', 'pancreatitis', 'hyperlipidemia (Type IV)', 'hyperlipidemia (Type V)', 'chylomicronemia', 'coronary heart disease', 'Type IIb hyperlipoproteinemia', 'low HDL cholesterol', 'elevated LDL cholesterol', 'elevated triglycerides', 'hypothyroidism', 'diabetes mellitus', 'familial hypertriglyceridemia', 'estrogen therapy']
Status: OK
Runtime: 3.73 seconds

======================================================================
[64/500] Record ID: 10096
Output: ['depression', 'major depressive disorder', 'major depressive episode', 'depressed mood', 'dysphoric mood']
Status: OK
Runtime: 11.47 seconds

======================================================================
[65/500] Record ID: 10099
Output: ['depression', 'Major Depressive Episode', 'dysphoric mood', 'suicidal ideation or attempts']
Status: OK
Runtime: 0.93 seconds

======================================================================
[66/500] Record ID: 1010
Output: ['Major Depressive Disorder', 'Major Depressive Disorder (DSM IV)', 'Generalized Anxiety Disorder', 'Generalized Anxiety Disorder (DSM IV)']
Status: OK
Runtime: 1.07 seconds

======================================================================
[67/500] Record ID: 10109
Output: ['serious or severe infections', 'methicillin resistant (beta lactam resistant) staphylococci', 'penicillin allergic patients', 'staphylococcal endocarditis', 'septicemia', 'bone infections', 'lower respiratory tract infections', 'skin, and skin structure infections', 'diphtheroid endocarditis', 'prosthetic valve endocarditis', 'antibiotic associated pseudomembranous colitis', 'staphylococcal enterocolitis']
Status: OK
Runtime: 2.41 seconds

======================================================================
[68/500] Record ID: 1011
Output: ['Asthma', 'Exercise Induced Bronchoconstriction', 'Allergic Rhinitis']
Status: OK
Runtime: 0.92 seconds

======================================================================
[69/500] Record ID: 10111
Output: ['hypertension', 'chronic stable angina', 'angina due to coronary artery spasm']
Status: OK
Runtime: 0.61 seconds

======================================================================
[70/500] Record ID: 10113
Output: ['pain', 'opioid tolerance', 'opioid abuse', 'opioid addiction', 'major depression']
Status: OK
Runtime: 0.84 seconds

======================================================================
[71/500] Record ID: 10114
Output: ['Influenza A virus', 'parkinsonism', 'drug induced extrapyramidal reactions', "idiopathic Parkinson's disease", 'Paralysis Agitans', 'postencephalitic parkinsonism', 'symptomatic parkinsonism', 'carbon monoxide intoxication', 'cerebral arteriosclerosis']
Status: OK
Runtime: 1.82 seconds

======================================================================
[72/500] Record ID: 10117
Output: ['Seizure Disorders', 'Lennox Gastaut syndrome', 'akinetic and myoclonic seizures', 'absence seizures', 'Panic Disorder', 'agoraphobia', 'Panic Disorder (DSM IV)', 'panic attacks', 'recurrent panic attacks']
Status: OK
Runtime: 1.72 seconds

======================================================================
[73/500] Record ID: 10119
Output: ['acute painful musculoskeletal conditions']
Status: OK
Runtime: 0.56 seconds

======================================================================
[74/500] Record ID: 1012
Output: ['Postherpetic Neuralgia', 'Epilepsy']
Status: OK
Runtime: 0.55 seconds

======================================================================
[75/500] Record ID: 10120
Output: ['Oropharyngeal candidiasis', 'esophageal candidiasis', 'Candida urinary tract infections', 'peritonitis', 'systemic Candida infections', 'candidemia', 'disseminated candidiasis', 'pneumonia', 'Cryptococcal meningitis', 'candidiasis', 'bone marrow transplantation']
Status: OK
Runtime: 1.48 seconds

======================================================================
[76/500] Record ID: 10127
Output: ['osteoarthritis', 'rheumatoid arthritis', 'ankylosing spondylitis']
Status: OK
Runtime: 0.7 seconds

======================================================================
[77/500] Record ID: 10129
Output: ['juvenile arthritis', 'rheumatoid arthritis', 'osteoarthritis']
Status: OK
Runtime: 0.62 seconds

======================================================================
[78/500] Record ID: 1013
Output: ['Major Depressive Disorder', 'Obsessive Compulsive Disorder', 'Bulimia Nervosa', 'Panic Disorder', 'Depressive Episodes Associated with Bipolar I Disorder']
Status: OK
Runtime: 1.25 seconds

======================================================================
[79/500] Record ID: 10132
Output: ['dyslipidemia', 'atherosclerotic vascular disease', 'Myocardial infarction', 'Unstable angina', 'Coronary revascularization procedures', 'Coronary Heart Disease', 'Hypercholesterolemia', 'Familial Hypercholesterolemia', 'hypertriglyceridemic', 'hyperlipoproteinemia', 'combined Hypercholesterolemia and hypertriglyceridemia']
Status: OK
Runtime: 3.71 seconds

======================================================================

In [20]:
print(
    df["gemma_status"]
    .value_counts(dropna=False)
)

gemma_status
OK               497
FORMAT_FAILED      3
Name: count, dtype: int64

In [21]:
failed_gemma = df[
    df["gemma_status"] == "FORMAT_FAILED"
]

display(
    failed_gemma[
        [
            "record_id",
            "gold_expert_mentions",
            "gemma_raw"
        ]
    ]
)

,record_id,gold_expert_mentions,gemma_raw
45,10029,"Infections of the ear, nose, and throat; Infec...","```json\n{""diseases"":[""ear infections"",""nose i..."
225,1432,Pharyngitis; Tonsillitis; Acute Bacterial Otit...,"```json\n{""diseases"":[""Pharyngitis Tonsillitis..."
258,12261,asthma; atopic dermatitis; contact dermatitis;...,"```json\n{""diseases"":[""allergic states"",""asthm..."

In [22]:
for i, row in failed_gemma.iterrows():

    print("=" * 80)
    print("RECORD ID:", row["record_id"])

    print()
    print("RAW RESPONSE:")
    print(repr(row["gemma_raw"]))

    print()

================================================================================
RECORD ID: 10029

RAW RESPONSE:
'```json\n{"diseases":["ear infections","nose infections","throat infections","pneumonia","Staphylococcus infections","influenza","genitourinary tract infections","coli infections","P. mirabilis infections","faecalis infections","skin infections","skin structure infections","lower respiratory tract infections","Streptococcus infections","hemolytic strains","gonorrhea","acute uncomplicated ano genital infections","urethral infections","duodenal ulcer disease","pylori infection"]}:}\n```'

================================================================================
RECORD ID: 1432

RAW RESPONSE:
'```json\n{"diseases":["Pharyngitis Tonsillitis","Acute Bacterial Otitis Media","Acute Bacterial Maxillary Sinusitis","Acute Bacterial Exacerbations of Chronic Bronchitis and Secondary Bacterial Infections of Acute Bronchitis","Uncomplicated Skin and Skin Structure Infections","Uncomplicated Urinary Tract Infections","Uncomplicated Gonorrhea","Early Lyme Disease (erythema migrans)"]}:}\n```'

================================================================================
RECORD ID: 12261

RAW RESPONSE:
'```json\n{"diseases":["allergic states","asthma","atopic dermatitis","contact dermatitis","drug hypersensitivity reactions","perennial or seasonal allergic rhinitis","serum sickness","bullous dermatitis herpetiformis","exfoliative erythroderma","mycosis fungoides","pemphigus","erythema multiforme (Stevens Johnson syndrome)","primary or secondary adrenocortical insufficiency","hydrocortisone or cortisone","synthetic mineralocorticoid analogs","congenital adrenal hyperplasia","hypercalcemia associated with cancer","nonsuppurative thyroiditis","regional enteritis","ulcerative colitis","acquired (autoimmune) hemolytic anemia","erythroid hypoplastic anemia (Diamond Blackfan anemia)","idiopathic thrombocytopenic purpura in adults","pure red cell aplasia","multiple sclerosis","cerebral edema","craniotomy","head injury","sympathetic ophthalmia","temporal arteritis","uveitis","ocular inflammatory conditions","idiopathic eosinophilic pneumonias","sarcoidosis","acute gouty arthritis","acute rheumatic carditis","ankylosing spondylitis","psoriatic arthritis","rheumatoid arthritis","juvenile rheumatoid arthritis","dermatomyositis","polymyositis","systemic lupus erythematosus","idiopathic nephrotic syndrome","lupus erythematosus","berylliosis","pulmonary tuberculosis","tuberculous meningitis","subarachnoid block","impending block","leukemias","lymphomas"]}:}\n```'

In [23]:
!pip -q install json-repair

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 2.9 MB/s eta 0:00:00

In [24]:
import json
from json_repair import repair_json


failed_indices = df.index[
    df["gemma_status"] == "FORMAT_FAILED"
].tolist()


for i in failed_indices:

    raw = str(
        df.at[i, "gemma_raw"]
    ).strip()

    print()
    print("=" * 70)
    print("Record:", df.at[i, "record_id"])

    try:

        # Remove markdown fences
        cleaned_raw = (
            raw
            .replace("```json", "")
            .replace("```", "")
            .strip()
        )

        # Repair JSON syntax only
        repaired = repair_json(
            cleaned_raw
        )

        parsed = json.loads(
            repaired
        )

        diseases = parsed["diseases"]


        # Remove exact duplicate strings only
        cleaned_diseases = []
        seen = set()

        for disease in diseases:

            disease = str(disease).strip()

            if (
                disease
                and disease.lower() not in seen
            ):

                seen.add(
                    disease.lower()
                )

                cleaned_diseases.append(
                    disease
                )


        df.at[
            i,
            "gemma_output"
        ] = json.dumps(
            cleaned_diseases,
            ensure_ascii=False
        )


        df.at[
            i,
            "gemma_status"
        ] = "OK_REPAIRED"


        print(
            "Recovered:",
            cleaned_diseases
        )


    except Exception as e:

        print(
            "Could not repair:",
            e
        )


df.to_excel(
    RESULT_FILE,
    index=False
)

print()
print("Saved:", RESULT_FILE)

======================================================================
Record: 10029
Recovered: ['ear infections', 'nose infections', 'throat infections', 'pneumonia', 'Staphylococcus infections', 'influenza', 'genitourinary tract infections', 'coli infections', 'P. mirabilis infections', 'faecalis infections', 'skin infections', 'skin structure infections', 'lower respiratory tract infections', 'Streptococcus infections', 'hemolytic strains', 'gonorrhea', 'acute uncomplicated ano genital infections', 'urethral infections', 'duodenal ulcer disease', 'pylori infection']

======================================================================
Record: 1432
Recovered: ['Pharyngitis Tonsillitis', 'Acute Bacterial Otitis Media', 'Acute Bacterial Maxillary Sinusitis', 'Acute Bacterial Exacerbations of Chronic Bronchitis and Secondary Bacterial Infections of Acute Bronchitis', 'Uncomplicated Skin and Skin Structure Infections', 'Uncomplicated Urinary Tract Infections', 'Uncomplicated Gonorrhea', 'Early Lyme Disease (erythema migrans)']

======================================================================
Record: 12261
Recovered: ['allergic states', 'asthma', 'atopic dermatitis', 'contact dermatitis', 'drug hypersensitivity reactions', 'perennial or seasonal allergic rhinitis', 'serum sickness', 'bullous dermatitis herpetiformis', 'exfoliative erythroderma', 'mycosis fungoides', 'pemphigus', 'erythema multiforme (Stevens Johnson syndrome)', 'primary or secondary adrenocortical insufficiency', 'hydrocortisone or cortisone', 'synthetic mineralocorticoid analogs', 'congenital adrenal hyperplasia', 'hypercalcemia associated with cancer', 'nonsuppurative thyroiditis', 'regional enteritis', 'ulcerative colitis', 'acquired (autoimmune) hemolytic anemia', 'erythroid hypoplastic anemia (Diamond Blackfan anemia)', 'idiopathic thrombocytopenic purpura in adults', 'pure red cell aplasia', 'multiple sclerosis', 'cerebral edema', 'craniotomy', 'head injury', 'sympathetic ophthalmia', 'temporal arteritis', 'uveitis', 'ocular inflammatory conditions', 'idiopathic eosinophilic pneumonias', 'sarcoidosis', 'acute gouty arthritis', 'acute rheumatic carditis', 'ankylosing spondylitis', 'psoriatic arthritis', 'rheumatoid arthritis', 'juvenile rheumatoid arthritis', 'dermatomyositis', 'polymyositis', 'systemic lupus erythematosus', 'idiopathic nephrotic syndrome', 'lupus erythematosus', 'berylliosis', 'pulmonary tuberculosis', 'tuberculous meningitis', 'subarachnoid block', 'impending block', 'leukemias', 'lymphomas']

Saved: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Gemma3_Results.xlsx

In [25]:
print(
    df["gemma_status"]
    .value_counts(dropna=False)
)

gemma_status
OK             497
OK_REPAIRED      3
Name: count, dtype: int64