In [ ]:
!nvidia-smi

Sat Aug 29 08:15:05 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [1]:
!ollama list

/bin/bash: line 1: ollama: command not found

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path

BASE_DIR = Path(
    "/content/drive/MyDrive/LLMValidation_LabeledIn"
)

INPUT_FILE = (
    BASE_DIR /
    "LabeledIn_LLM_Benchmark.xlsx"
)

RESULT_CSV = (
    BASE_DIR /
    "LabeledIn_LLM_Results.csv"
)

RESULT_XLSX = (
    BASE_DIR /
    "LabeledIn_LLM_Results.xlsx"
)

print("Folder:", BASE_DIR)
print("Benchmark exists:", INPUT_FILE.exists())

Folder: /content/drive/MyDrive/LLMValidation_LabeledIn
Benchmark exists: True

In [ ]:
!pip -q install pandas openpyxl requests

In [ ]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Installing ollama to /usr/local
ERROR: This version requires zstd for extraction. Please install zstd and try again:
  - Debian/Ubuntu: sudo apt-get install zstd
  - RHEL/CentOS/Fedora: sudo dnf install zstd
  - Arch: sudo pacman -S zstd

In [ ]:
!apt-get update -qq
!apt-get install -y zstd

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 77 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 2s (331 kB/s)
Selecting previously unselected package zstd.
(Reading database ... 122579 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
!ollama --version

Warning: could not connect to a running Ollama instance
Warning: client version is 0.33.2

In [ ]:
!nvidia-smi

Sat Aug 29 08:19:46 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
!apt-get install -y pciutils

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpci3 pci.ids
The following NEW packages will be installed:
  libpci3 pci.ids pciutils
0 upgraded, 3 newly installed, 0 to remove and 77 not upgraded.
Need to get 343 kB of archives.
After this operation, 1,581 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pci.ids all 0.0~2022.01.22-1ubuntu0.1 [251 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpci3 amd64 1:3.7.0-6 [28.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 pciutils amd64 1:3.7.0-6 [63.6 kB]
Fetched 343 kB in 2s (191 kB/s)
Selecting previously unselected package pci.ids.
(Reading database ... 122600 files and directories currently installed.)
Preparing to unpack .../pci.ids_0.0~2022.01.22-1ubuntu0.1_all.deb ...
Unpacking pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Selecting previously unselected package libpci3:amd64.
Preparing to unpack .../libpci3_1%3a3.7.0-6_amd64.deb ...
Unpacking libpci3:amd64 (1:3.7.0-6) ...
Selecting previously unselected package pciutils.
Preparing to unpack .../pciutils_1%3a3.7.0-6_amd64.deb ...
Unpacking pciutils (1:3.7.0-6) ...
Setting up pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Setting up libpci3:amd64 (1:3.7.0-6) ...
Setting up pciutils (1:3.7.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

In [ ]:
!lspci | grep -i nvidia

00:04.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)

In [ ]:
import subprocess
import time
import requests

ollama_process = subprocess.Popen(
    ["ollama", "serve"],
    stdout=open("/content/ollama.log", "w"),
    stderr=subprocess.STDOUT
)

time.sleep(5)

try:
    response = requests.get(
        "http://127.0.0.1:11434/api/tags",
        timeout=10
    )

    print("Ollama server status:", response.status_code)

except Exception as e:
    print("Could not connect:", e)

Ollama server status: 200

In [ ]:
!ollama list

NAME    ID    SIZE    MODIFIED

In [ ]:
!ollama pull koesn/llama3-openbiollm-8b:q5_K_M

In [2]:
!ollama list

/bin/bash: line 1: ollama: command not found

In [ ]:
!nvidia-smi

Sat Aug 29 08:23:34 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
!ollama ps

NAME    ID    SIZE    PROCESSOR    CONTEXT    UNTIL

In [ ]:
!ollama pull koesn/llama3-openbiollm-8b:q5_K_M

In [ ]:
!ollama list

NAME                                 ID              SIZE      MODIFIED
koesn/llama3-openbiollm-8b:q5_K_M    27cbaac5fd96    5.7 GB    14 seconds ago

In [ ]:
!ollama ps

NAME    ID    SIZE    PROCESSOR    CONTEXT    UNTIL

In [ ]:
!ollama list

NAME                                 ID              SIZE      MODIFIED
koesn/llama3-openbiollm-8b:q5_K_M    27cbaac5fd96    5.7 GB    About a minute ago

In [ ]:
import requests

MODEL = "koesn/llama3-openbiollm-8b:q5_K_M"
URL = "http://127.0.0.1:11434/api/generate"

system_message = """
You are a biomedical information extraction system.
Follow the user's extraction instructions exactly.
Return only the requested JSON output.
""".strip()

user_message = """
Extract all clinical conditions for which the drug is explicitly indicated.

Return ONLY valid JSON:

{"diseases":["condition 1","condition 2"]}

Text:
Metoprolol is indicated for the treatment of hypertension and angina pectoris.
""".strip()

prompt = (
    "<|begin_of_text|>"
    "<|start_header_id|>system<|end_header_id|>\n\n"
    + system_message
    + "<|eot_id|>"
    "<|start_header_id|>user<|end_header_id|>\n\n"
    + user_message
    + "<|eot_id|>"
    "<|start_header_id|>assistant<|end_header_id|>\n\n"
)

payload = {
    "model": MODEL,
    "prompt": prompt,
    "raw": True,
    "stream": False,
    "options": {
        "temperature": 0.1,
        "num_ctx": 4096,
        "num_predict": 200,
        "stop": [
            "<|eot_id|>",
            "<|end_of_text|>"
        ]
    }
}

response = requests.post(
    URL,
    json=payload,
    timeout=240
)

response.raise_for_status()

result = response.json()

print(result["response"])

{"diseases":["hypertension","angina pectoris"]}

In [ ]:
!ollama ps

NAME                                 ID              SIZE      PROCESSOR    CONTEXT    UNTIL
koesn/llama3-openbiollm-8b:q5_K_M    27cbaac5fd96    6.0 GB    100% GPU     4096       4 minutes from now

In [ ]:
import requests

MODEL = "koesn/llama3-openbiollm-8b:q5_K_M"
URL = "http://127.0.0.1:11434/api/generate"

system_message = """
You are a biomedical information extraction system.
Follow the user's extraction instructions exactly.
Return only the requested JSON output.
""".strip()

user_message = """
Extract all clinical conditions for which the drug is explicitly indicated.

Return ONLY valid JSON:

{"diseases":["condition 1","condition 2"]}

Text:
Metoprolol is indicated for the treatment of hypertension and angina pectoris.
""".strip()

prompt = (
    "<|begin_of_text|>"
    "<|start_header_id|>system<|end_header_id|>\n\n"
    + system_message
    + "<|eot_id|>"
    "<|start_header_id|>user<|end_header_id|>\n\n"
    + user_message
    + "<|eot_id|>"
    "<|start_header_id|>assistant<|end_header_id|>\n\n"
)

payload = {
    "model": MODEL,
    "prompt": prompt,
    "raw": True,
    "stream": False,
    "options": {
        "temperature": 0.1,
        "num_ctx": 4096,
        "num_predict": 300,
        "stop": [
            "<|eot_id|>",
            "<|end_of_text|>"
        ]
    }
}

response = requests.post(
    URL,
    json=payload,
    timeout=240
)

response.raise_for_status()

print(response.json()["response"])

{"diseases":["hypertension","angina pectoris"]}

In [ ]:
!ollama ps

NAME                                 ID              SIZE      PROCESSOR    CONTEXT    UNTIL
koesn/llama3-openbiollm-8b:q5_K_M    27cbaac5fd96    6.0 GB    100% GPU     4096       4 minutes from now

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from pathlib import Path

INPUT_FILE = Path(
    "/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_LLM_Benchmark.xlsx"
)

RESULT_FILE = Path(
    "/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_OpenBioLLM_Results.xlsx"
)

print("Input exists:", INPUT_FILE.exists())
print("Input:", INPUT_FILE)

Input exists: True
Input: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_LLM_Benchmark.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel(
    INPUT_FILE,
    sheet_name="Benchmark"
)

print("Number of records:", len(df))

display(
    df[
        [
            "record_id",
            "indication_text",
            "gold_expert_mentions",
            "gold_umls_cuis"
        ]
    ].head()
)

Number of records: 500

,record_id,indication_text,gold_expert_mentions,gold_umls_cuis
0,10004,Pantoprazole sodium delayed release tablets ar...,Erosive Esophagitis; Gastroesophageal Reflux D...,C0267055; C0017168; C0043515
1,10008,Anxiety Disorders Alprazolam tablets are indic...,Anxiety Disorders; anxiety disorder; Anxiety; ...,C0003469; C0338908; C0030319; C0001818
2,10012,Amiodarone hydrochloride injection is indicate...,ventricular fibrillation; ventricular tachycar...,C0042510; C0042514
3,10016,"Clobetasol propionate foam, 0.05% is a super p...",dermatoses; plaque type psoriasis,C0037274; C0406317
4,10017,Metaxalone tablets are indicated as an adjunct...,"acute, painful",C0184567

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("Saved to:", RESULT_FILE)

Saved to: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_OpenBioLLM_Results.xlsx

In [ ]:
import json
import time
import requests

MODEL = "koesn/llama3-openbiollm-8b:q5_K_M"
URL = "http://127.0.0.1:11434/api/generate"

SYSTEM_MESSAGE = """
You are a biomedical information extraction system.
Follow the user's extraction instructions exactly.
Return only the requested JSON output.
""".strip()


EXTRACTION_TEMPLATE = """
Extract ALL diseases, disorders, syndromes, symptoms, or clinical conditions
for which the drug is explicitly indicated in the following
Indications and Usage text.

Rules:

1. Read the entire supplied text.
2. Include every explicitly stated clinical indication.
3. Include symptoms or clinical conditions when explicitly indicated
   for treatment, prevention, management, or relief.
4. Preserve clinically meaningful disease subtypes and modifiers.
5. Use wording from the supplied text as closely as possible.
6. Do not intentionally normalize or generalize disease names.
7. Do not infer conditions that are not explicitly supported by the text.
8. Exclude conditions explicitly stated as NOT indicated or NOT recommended.
9. Exclude causative organisms when they merely describe the cause of infection.
10. Exclude mechanisms, procedures, dosing information,
    treatment regimens, and patient demographics.
11. Remove duplicate clinical conditions.

Return ONLY valid JSON:

{{"diseases":["condition 1","condition 2"]}}

If there are genuinely no indications:

{{"diseases":[]}}

INDICATIONS AND USAGE:

{indication_text}
""".strip()

In [ ]:
def parse_output(raw_output):

    raw_output = raw_output.strip()

    try:
        parsed = json.loads(raw_output)

    except json.JSONDecodeError:

        start = raw_output.find("{")
        end = raw_output.rfind("}")

        if start == -1 or end == -1:
            raise ValueError("No JSON object found in model response.")

        parsed = json.loads(
            raw_output[start:end + 1]
        )

    if "diseases" not in parsed:
        raise ValueError("JSON does not contain 'diseases'.")

    diseases = parsed["diseases"]

    if not isinstance(diseases, list):
        raise ValueError("'diseases' must be a list.")

    cleaned = []
    seen = set()

    for disease in diseases:

        if not isinstance(disease, str):
            continue

        disease = disease.strip()

        if not disease:
            continue

        key = disease.lower()

        if key not in seen:
            seen.add(key)
            cleaned.append(disease)

    return cleaned

In [ ]:
def extract_openbiollm(indication_text):

    user_message = EXTRACTION_TEMPLATE.format(
        indication_text=indication_text
    )

    prompt = (
        "<|begin_of_text|>"
        "<|start_header_id|>system<|end_header_id|>\n\n"
        + SYSTEM_MESSAGE
        + "<|eot_id|>"
        "<|start_header_id|>user<|end_header_id|>\n\n"
        + user_message
        + "<|eot_id|>"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
    )

    payload = {
        "model": MODEL,
        "prompt": prompt,
        "raw": True,
        "stream": False,

        "options": {
            "temperature": 0.1,
            "num_ctx": 4096,
            "num_predict": 1000,

            "stop": [
                "<|eot_id|>",
                "<|end_of_text|>"
            ]
        }
    }

    start_time = time.time()

    response = requests.post(
        URL,
        json=payload,
        timeout=240
    )

    response.raise_for_status()

    raw_output = response.json()["response"]

    diseases = parse_output(raw_output)

    runtime = round(
        time.time() - start_time,
        2
    )

    return diseases, raw_output, runtime

In [ ]:
for column in [
    "openbiollm_output",
    "openbiollm_raw",
    "openbiollm_status",
    "openbiollm_runtime_sec"
]:
    if column not in df.columns:
        df[column] = ""


for i in range(5):

    record_id = df.loc[i, "record_id"]
    indication_text = str(
        df.loc[i, "indication_text"]
    )

    print()
    print("=" * 70)
    print(f"RECORD {i + 1}/5")
    print("Record ID:", record_id)

    print()
    print("EXPERT GOLD:")
    print(
        df.loc[i, "gold_expert_mentions"]
    )

    try:

        diseases, raw, runtime = extract_openbiollm(
            indication_text
        )

        df.at[i, "openbiollm_output"] = json.dumps(
            diseases,
            ensure_ascii=False
        )

        df.at[i, "openbiollm_raw"] = raw

        df.at[i, "openbiollm_status"] = (
            "OK"
            if len(diseases) > 0
            else "OK_EMPTY"
        )

        df.at[i, "openbiollm_runtime_sec"] = runtime

        print()
        print("MODEL OUTPUT:")
        print(diseases)

        print("Runtime:", runtime, "seconds")

    except Exception as e:

        df.at[i, "openbiollm_status"] = "FAILED"
        df.at[i, "openbiollm_raw"] = str(e)

        print()
        print("ERROR:")
        print(e)


df.to_excel(
    RESULT_FILE,
    index=False
)

print()
print("Saved to:")
print(RESULT_FILE)

======================================================================
RECORD 1/5
Record ID: 10004

EXPERT GOLD:
Erosive Esophagitis; Gastroesophageal Reflux Disease; GERD; Zollinger Ellison Syndrome

/tmp/ipykernel_1804/3642900359.py:35: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '["Erosive Esophagitis", "GERD", "Pathological Hypersecretory Conditions including Zollinger Ellison Syndrome"]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, "openbiollm_output"] = json.dumps(
/tmp/ipykernel_1804/3642900359.py:42: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'OK' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, "openbiollm_status"] = (

MODEL OUTPUT:
['Erosive Esophagitis', 'GERD', 'Pathological Hypersecretory Conditions including Zollinger Ellison Syndrome']
Runtime: 5.25 seconds

======================================================================
RECORD 2/5
Record ID: 10008

EXPERT GOLD:
Anxiety Disorders; anxiety disorder; Anxiety; Anxiety associated with depression; Panic Disorder; agoraphobia

MODEL OUTPUT:
['Generalized Anxiety Disorder', 'Panic Disorder']
Runtime: 1.04 seconds

======================================================================
RECORD 3/5
Record ID: 10012

EXPERT GOLD:
ventricular fibrillation; ventricular tachycardia; VT; VF

MODEL OUTPUT:
['Ventricular Fibrillation']
Runtime: 0.62 seconds

======================================================================
RECORD 4/5
Record ID: 10016

EXPERT GOLD:
dermatoses; plaque type psoriasis

MODEL OUTPUT:
['Plaque Psoriasis']
Runtime: 0.48 seconds

======================================================================
RECORD 5/5
Record ID: 10017

EXPERT GOLD:
acute, painful

MODEL OUTPUT:
[]
Runtime: 0.27 seconds

Saved to:
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_OpenBioLLM_Results.xlsx

In [ ]:
display(
    df[
        [
            "record_id",
            "gold_expert_mentions",
            "openbiollm_output",
            "openbiollm_status",
            "openbiollm_runtime_sec"
        ]
    ].head(5)
)

,record_id,gold_expert_mentions,openbiollm_output,openbiollm_status,openbiollm_runtime_sec
0,10004,Erosive Esophagitis; Gastroesophageal Reflux D...,"[""Erosive Esophagitis"", ""GERD"", ""Pathological ...",OK,5.25
1,10008,Anxiety Disorders; anxiety disorder; Anxiety; ...,"[""Generalized Anxiety Disorder"", ""Panic Disord...",OK,1.04
2,10012,ventricular fibrillation; ventricular tachycar...,"[""Ventricular Fibrillation""]",OK,0.62
3,10016,dermatoses; plaque type psoriasis,"[""Plaque Psoriasis""]",OK,0.48
4,10017,"acute, painful",[],OK_EMPTY,0.27

In [ ]:
!ollama ps

NAME    ID    SIZE    PROCESSOR    CONTEXT    UNTIL

In [ ]:
def run_all_openbiollm():

    total = len(df)

    for i in range(total):

        record_id = df.loc[i, "record_id"]

        # Skip records already completed
        current_status = str(
            df.at[i, "openbiollm_status"]
        ).strip()

        if current_status in ["OK", "OK_EMPTY"]:

            print(
                f"[{i + 1}/{total}] "
                f"Record {record_id} - already completed"
            )

            continue


        indication_text = str(
            df.loc[i, "indication_text"]
        )


        print()
        print("=" * 70)
        print(
            f"[{i + 1}/{total}] "
            f"Record ID: {record_id}"
        )


        success = False
        last_error = ""


        # Try maximum 3 times if there is an error
        for attempt in range(1, 4):

            try:

                diseases, raw, runtime = extract_openbiollm(
                    indication_text
                )


                df.at[
                    i,
                    "openbiollm_output"
                ] = json.dumps(
                    diseases,
                    ensure_ascii=False
                )


                df.at[
                    i,
                    "openbiollm_raw"
                ] = raw


                df.at[
                    i,
                    "openbiollm_status"
                ] = (
                    "OK"
                    if len(diseases) > 0
                    else "OK_EMPTY"
                )


                df.at[
                    i,
                    "openbiollm_runtime_sec"
                ] = runtime


                print(
                    "Output:",
                    diseases
                )

                print(
                    "Runtime:",
                    runtime,
                    "seconds"
                )


                success = True
                break


            except Exception as e:

                last_error = str(e)

                print(
                    f"Attempt {attempt}/3 failed:",
                    e
                )

                time.sleep(2)


        if not success:

            df.at[
                i,
                "openbiollm_status"
            ] = "FAILED"

            df.at[
                i,
                "openbiollm_raw"
            ] = last_error


        # Save checkpoint every 20 records
        if (
            (i + 1) % 20 == 0
            or
            i == total - 1
        ):

            df.to_excel(
                RESULT_FILE,
                index=False
            )

            print(
                ">>> CHECKPOINT SAVED TO GOOGLE DRIVE"
            )


    # Final save
    df.to_excel(
        RESULT_FILE,
        index=False
    )


    print()
    print("=" * 70)
    print("OPENBIOLLM FINISHED")
    print("=" * 70)

    print(
        "Results saved to:"
    )

    print(
        RESULT_FILE
    )

In [ ]:
run_all_openbiollm()

[1/500] Record 10004 - already completed
[2/500] Record 10008 - already completed
[3/500] Record 10012 - already completed
[4/500] Record 10016 - already completed
[5/500] Record 10017 - already completed

======================================================================
[6/500] Record ID: 1001
Output: ['Hypertension', 'Angina Pectoris', 'Myocardial Infarction']
Runtime: 4.98 seconds

======================================================================
[7/500] Record ID: 10140
Output: ['Major Depressive Disorder']
Runtime: 0.63 seconds

======================================================================
[8/500] Record ID: 10146
Output: ['Short term insomnia']
Runtime: 0.43 seconds

======================================================================
[9/500] Record ID: 10153
Output: ['Anxiety', 'Pruritus', 'Contact dermatoses', 'Urticaria', 'Atopic dermatoses', 'Histamine mediated pruritus']
Runtime: 1.2 seconds

======================================================================
[10/500] Record ID: 10157
Output: ["Parkinson's disease"]
Runtime: 0.41 seconds

======================================================================
[11/500] Record ID: 10173
Output: ['Epilepsy', 'Juvenile Myoclonic Epilepsy', 'Idiopathic Generalized Epilepsy']
Runtime: 0.99 seconds

======================================================================
[12/500] Record ID: 1024
Output: ['Head Lice Infestation']
Runtime: 0.45 seconds

======================================================================
[13/500] Record ID: 10263
Output: []
Runtime: 1.28 seconds

======================================================================
[14/500] Record ID: 10268
Output: ['Essential hypertension']
Runtime: 0.44 seconds

======================================================================
[15/500] Record ID: 10295
Output: ['Megaloblastic anemias', 'Anemias of nutritional origin', 'Pregnancy', 'Infancy', 'Childhood']
Runtime: 0.94 seconds

======================================================================
[16/500] Record ID: 10303
Output: ['Benign Prostatic Hyperplasia']
Runtime: 0.45 seconds

======================================================================
[17/500] Record ID: 10311
Output: ['Venous Thrombosis', 'Pulmonary Embolism', 'Atrial Fibrillation', 'Cardiac Valve Replacement', 'Myocardial Infarction']
Runtime: 1.25 seconds

======================================================================
[18/500] Record ID: 10312
Output: ['type 2 diabetes mellitus']
Runtime: 0.45 seconds

======================================================================
[19/500] Record ID: 10316
Output: ['Benign Prostatic Hyperplasia (BPH)', 'Hypertension']
Runtime: 0.91 seconds

======================================================================
[20/500] Record ID: 10318
Output: ['psoriasis']
Runtime: 0.52 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[21/500] Record ID: 10319
Output: ['Chemotherapy Induced Nausea and Vomiting', 'Radiation Induced Nausea and Vomiting', 'Postoperative Nausea and Vomiting']
Runtime: 1.38 seconds

======================================================================
[22/500] Record ID: 10320
Output: ['intermittent claudication']
Runtime: 0.41 seconds

======================================================================
[23/500] Record ID: 10322
Output: ['Hyperkalemia']
Runtime: 0.35 seconds

======================================================================
[24/500] Record ID: 10445
Output: ['Cough']
Runtime: 0.29 seconds

======================================================================
[25/500] Record ID: 11458
Output: ['Major Depressive Disorder', 'Seasonal Affective Disorder']
Runtime: 0.97 seconds

======================================================================
[26/500] Record ID: 3022
Output: ['Asthma']
Runtime: 0.45 seconds

======================================================================
[27/500] Record ID: 3533
Output: ['Motion sickness', 'Nausea and vomiting associated with anesthesia and surgery']
Runtime: 0.63 seconds

======================================================================
[28/500] Record ID: 3750
Output: ['Schizophrenia']
Runtime: 0.43 seconds

======================================================================
[29/500] Record ID: 4288
Output: ['pulmonary arterial hypertension']
Runtime: 0.44 seconds

======================================================================
[30/500] Record ID: 4292
Output: ['Renal Homotransplantation', 'Rheumatoid Arthritis']
Runtime: 0.83 seconds

======================================================================
[31/500] Record ID: 4346
Output: ['gestational choriocarcinoma', 'chorioadenoma destruens', 'hydatidiform mole', 'acute lymphocytic leukemia', 'meningeal leukemia', 'breast cancer', 'epidermoid cancers of the head and neck', 'advanced mycosis fungoides (cutaneous T cell lymphoma)', 'lung cancer', 'non Hodgkin s lymphomas', 'non metastatic osteosarcoma', 'psoriasis', 'rheumatoid arthritis including polyarticular course juvenile rheumatoid arthritis']
Runtime: 3.62 seconds

======================================================================
[32/500] Record ID: 4498
Output: ['Overactive Bladder']
Runtime: 0.44 seconds

======================================================================
[33/500] Record ID: 4706
Output: ['Reversible obstructive airway disease']
Runtime: 0.44 seconds

======================================================================
[34/500] Record ID: 490
Output: ['Attention Deficit Disorders', 'Narcolepsy']
Runtime: 0.86 seconds

======================================================================
[35/500] Record ID: 4976
Output: ['Hypogonadism', 'Hypogonadotropic hypogonadism']
Runtime: 1.03 seconds

======================================================================
[36/500] Record ID: 558
Output: ['hypertension']
Runtime: 0.37 seconds

======================================================================
[37/500] Record ID: 5610
Output: ['hypertension', 'angina']
Runtime: 0.42 seconds

======================================================================
[38/500] Record ID: 6071
Output: ['Restless Legs Syndrome', 'Postherpetic Neuralgia']
Runtime: 0.61 seconds

======================================================================
[39/500] Record ID: 6412
Attempt 1/3 failed: Extra data: line 3 column 1 (char 35)
Attempt 2/3 failed: Extra data: line 3 column 1 (char 35)
Output: ['Opioid addiction']
Runtime: 0.73 seconds

======================================================================
[40/500] Record ID: 10
Output: ['Hypertension']
Runtime: 0.37 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[41/500] Record ID: 1000
Attempt 1/3 failed: Expecting ',' delimiter: line 1 column 1987 (char 1986)
Attempt 2/3 failed: Expecting ',' delimiter: line 1 column 1987 (char 1986)
Attempt 3/3 failed: Expecting ',' delimiter: line 1 column 1987 (char 1986)

======================================================================
[42/500] Record ID: 10000
Output: ['Depression']
Runtime: 0.59 seconds

======================================================================
[43/500] Record ID: 10003
Output: ['Epilepsy', 'Trigeminal Neuralgia']
Runtime: 0.75 seconds

======================================================================
[44/500] Record ID: 10021
Output: ['Left Ventricular Dysfunction Following Myocardial Infarction', 'Hypertension']
Runtime: 0.91 seconds

======================================================================
[45/500] Record ID: 10023
Output: ['Rosacea']
Runtime: 0.33 seconds

======================================================================
[46/500] Record ID: 10029
Output: ['Streptococcus spp.', 'Staphylococcus spp.', 'S . pneumoniae', 'Influenzae', 'Gonorrhoeae', 'Helicobacter pylori', 'Coli', 'P. mirabilis', 'Faecalis']
Runtime: 2.47 seconds

======================================================================
[47/500] Record ID: 10036
Output: ["Parkinson's Disease", 'Restless Legs Syndrome']
Runtime: 0.81 seconds

======================================================================
[48/500] Record ID: 10041
Output: ['Type 2 Diabetes Mellitus']
Runtime: 0.5 seconds

======================================================================
[49/500] Record ID: 10043
Attempt 1/3 failed: Expecting ',' delimiter: line 1 column 296 (char 295)
Output: ['Allergic reaction', 'Anaphylaxis', 'Nausea and vomiting (postoperative)', 'Postoperative pain (adjunctive therapy)', 'Sedation (preoperative, postoperative, and obstetric)', 'Motion sickness', 'Allergic conditions (uncomplicated)']
Runtime: 2.03 seconds

======================================================================
[50/500] Record ID: 10048
Output: ['Depression']
Runtime: 0.39 seconds

======================================================================
[51/500] Record ID: 1005
Output: ['asthma', 'chronic bronchitis', 'emphysema']
Runtime: 0.73 seconds

======================================================================
[52/500] Record ID: 10054
Output: ['Hypertension']
Runtime: 0.41 seconds

======================================================================
[53/500] Record ID: 10059
Output: ['Hypothyroidism', 'Euthyroid Goiter', 'Thyroid Nodules', "Hashimoto's Thyroiditis", 'Multinodular Goiter', 'Thyrotropin Dependent Well Differentiated Thyroid Cancer']
Runtime: 2.07 seconds

======================================================================
[54/500] Record ID: 1006
Output: ['type 2 diabetes mellitus']
Runtime: 0.53 seconds

======================================================================
[55/500] Record ID: 10072
Output: ['Attention Deficit Hyperactivity Disorder (ADHD)']
Runtime: 1.16 seconds

======================================================================
[56/500] Record ID: 10073
Output: ['Muscle Spasm']
Runtime: 0.66 seconds

======================================================================
[57/500] Record ID: 10082
Output: ['Acute otitis media caused by Haemophilus influenzae, Moraxella catarrhalis or Streptococcus pneumoniae', 'Community acquired pneumonia due to Chlamydia pneumoniae, Haemophilus influenzae, Mycoplasma pneumoniae or Streptococcus pneumoniae', 'Pharyngitis tonsillitis caused by Streptococcus pyogenes as an alternative to first line therapy in individuals who cannot use first line therapy', 'Uncomplicated skin and skin structure infections due to Staphylococcus aureus, Streptococcus pyogenes, or Streptococcus agalactiae', 'Urethritis and cervicitis due to Chlamydia trachomatis or Neisseria gonorrhoeae', 'Genital ulcer disease in men due to Haemophilus ducreyi (chancroid)']
Runtime: 7.87 seconds

======================================================================
[58/500] Record ID: 10084
Output: ['Depression', 'Anxiety', 'Psychoneurotic patients with Depression and/or anxiety', 'Depression and/or anxiety associated with alcoholism', 'Depression and/or anxiety associated with organic disease', 'Psychotic depressive disorders with associated anxiety including involutional depression and manic depressive disorders']
Runtime: 2.48 seconds

======================================================================
[59/500] Record ID: 10087
Output: ['Hypertension', 'Chronic Stable Angina', 'Vasospastic Angina', 'Angiographically Documented CAD']
Runtime: 1.29 seconds

======================================================================
[60/500] Record ID: 1009
Output: ['Hypertension', 'Left Ventricular Hypertrophy', 'Nephropathy in Type 2 Diabetic Patients']
Runtime: 1.28 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[61/500] Record ID: 10090
Output: ['Acute Pain']
Runtime: 0.84 seconds

======================================================================
[62/500] Record ID: 10091
Output: ['Primary hypogonadism (congenital or acquired) testicular failure due to cryptorchidism, bilateral torsion, orchitis, vanishing testis syndrome; or orchidectomy.', 'Hypogonadotropic hypogonadism (congenital or acquired) idiopathic gonadotropin or LHRH deficiency, or pituitary hypothalamic injury from tumors, trauma, or radiation.']
Runtime: 3.56 seconds

======================================================================
[63/500] Record ID: 10093
Output: []
Runtime: 1.2 seconds

======================================================================
[64/500] Record ID: 10096
Output: ['Major Depressive Disorder']
Runtime: 0.81 seconds

======================================================================
[65/500] Record ID: 10099
Output: ['Major Depressive Disorder']
Runtime: 0.6 seconds

======================================================================
[66/500] Record ID: 1010
Output: ['Major Depressive Disorder', 'Generalized Anxiety Disorder']
Runtime: 0.88 seconds

======================================================================
[67/500] Record ID: 10109
Output: ['Methicillin-resistant staphylococcal infection', 'Staphylococcal endocarditis', 'Septicemia', 'Bone infections', 'Lower respiratory tract infections', 'Skin and skin structure infections', 'Diphtheroid endocarditis', 'Prosthetic valve endocarditis', 'Antibiotic associated pseudomembranous colitis produced by Clostridium difficile', 'Staphylococcal enterocolitis']
Runtime: 3.97 seconds

======================================================================
[68/500] Record ID: 1011
Output: ['Asthma', 'Exercise Induced Bronchoconstriction', 'Allergic Rhinitis']
Runtime: 1.17 seconds

======================================================================
[69/500] Record ID: 10111
Output: ['Hypertension', 'Angina']
Runtime: 0.99 seconds

======================================================================
[70/500] Record ID: 10113
Output: ['opioid tolerant pain']
Runtime: 0.86 seconds

======================================================================
[71/500] Record ID: 10114
Output: ['Influenza A virus', "Parkinson's disease", 'Drug induced extrapyramidal reactions']
Runtime: 1.71 seconds

======================================================================
[72/500] Record ID: 10117
Output: ['Seizure Disorders', 'Panic Disorder']
Runtime: 1.09 seconds

======================================================================
[73/500] Record ID: 10119
Output: ['Acute painful musculoskeletal conditions']
Runtime: 0.62 seconds

======================================================================
[74/500] Record ID: 1012
Output: ['Postherpetic Neuralgia', 'Epilepsy']
Runtime: 0.7 seconds

======================================================================
[75/500] Record ID: 10120
Output: ['Oropharyngeal and esophageal candidiasis', 'Cryptococcal meningitis']
Runtime: 1.19 seconds

======================================================================
[76/500] Record ID: 10127
Output: ['Osteoarthritis', 'Rheumatoid arthritis', 'Ankylosing spondylitis']
Runtime: 1.19 seconds

======================================================================
[77/500] Record ID: 10129
Output: ['juvenile arthritis', 'rheumatoid arthritis', 'osteoarthritis']
Runtime: 0.86 seconds

======================================================================
[78/500] Record ID: 1013
Output: ['Major Depressive Disorder', 'Obsessive Compulsive Disorder', 'Bulimia Nervosa', 'Panic Disorder', 'Bipolar I Disorder (Depressive Episodes)']
Runtime: 2.01 seconds

======================================================================
[79/500] Record ID: 10132
Attempt 1/3 failed: No JSON object found in model response.
Output: ['Hypercholesterolemia', 'Hyperlipidemia', 'Hyperlipoproteinemia', 'Hypertriglyceridemia', 'Coronary Heart Disease', 'Atherosclerotic Vascular Disease', 'Myocardial Infarction', 'Unstable Angina', 'Coronary Revascularization Procedures', 'Hypothyroidism', 'Nephrotic Syndrome', 'Dysproteinemias', 'Obstructive Liver Disease', 'Other Drug Therapy', 'Alcoholism', 'Type IIa Hyperlipoproteinemia', 'Type IIb Hyperlipoproteinemia', 'Type III Hyperlipoproteinemia', 'Type IV Hyperlipoproteinemia', 'Type V Hyperlipoproteinemia']
Runtime: 5.15 seconds

======================================================================
[80/500] Record ID: 1015
Output: ['rheumatoid arthritis', 'osteoarthritis', 'pain', 'primary dysmenorrhea']
Runtime: 1.26 seconds
>>> CHECKPOINT SAVED TO GOOGLE DRIVE

======================================================================
[81/500] Record ID: 10184
Output: ['Schizophrenia', 'Bipolar I Disorder', 'Irritability associated with Autistic Disorder']
Runtime: 1.63 seconds

======================================================================
[82/500] Record ID: 10185
Output: ['Streptococcal infections', 'Otitis media', 'Skin and skin structure infections', 'Bone infections', 'Genitourinary tract infections']
Runtime: 1.74 seconds

======================================================================
[83/500] Record ID: 10193
Output: ['Major Depressive Disorder']
Runtime: 0.75 seconds

======================================================================
[84/500] Record ID: 102
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.

======================================================================
[85/500] Record ID: 10205
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.

======================================================================
[86/500] Record ID: 10218
Output: ['Cold Sores (Herpes Labialis)', 'Genital Herpes', 'Herpes Zoster']
Runtime: 2.03 seconds

======================================================================
[87/500] Record ID: 10291
Output: ['dermatoses']
Runtime: 0.56 seconds

======================================================================
[88/500] Record ID: 10749
Output: ['Postherpetic neuralgia']
Runtime: 0.51 seconds

======================================================================
[89/500] Record ID: 10829
Output: ['mild dysenteries', 'diverticulitis', 'gastric secretion', 'visceral spasm and hypermotility in cystitis', 'pylorospasm and associated abdominal cramps', 'biliary and renal colic', 'acute rhinitis', 'peptic ulcer', 'irritable bowel syndrome', 'acute enterocolitis', 'other functional gastrointestinal disorders']
Runtime: 3.03 seconds

======================================================================
[90/500] Record ID: 11018
Output: ['Moderate to severe pain such as that due to surgery, cancer, trauma (soft tissue and bone), biliary colic, myocardial infarction, burns, renal colic']
Runtime: 1.69 seconds

======================================================================
[91/500] Record ID: 1104
Output: ['rheumatoid arthritis', 'osteoarthritis', 'ankylosing spondylitis']
Runtime: 0.94 seconds

======================================================================
[92/500] Record ID: 11157
Output: ['Atopic Dermatitis', 'Contact Dermatitis', 'Eczema', 'Psoriasis', 'Seborrheic Dermatitis']
Runtime: 1.22 seconds

======================================================================
[93/500] Record ID: 11274
Output: []
Runtime: 0.29 seconds

======================================================================
[94/500] Record ID: 11384
Output: []
Runtime: 0.33 seconds

======================================================================
[95/500] Record ID: 1143
Output: ['Chemotherapy induced nausea and vomiting', 'Postoperative nausea and vomiting']
Runtime: 0.98 seconds

======================================================================
[96/500] Record ID: 1147

In [ ]:
run_all_openbiollm()

[1/500] Record 10004 - already completed
[2/500] Record 10008 - already completed
[3/500] Record 10012 - already completed
[4/500] Record 10016 - already completed
[5/500] Record 10017 - already completed
[6/500] Record 1001 - already completed
[7/500] Record 10140 - already completed
[8/500] Record 10146 - already completed
[9/500] Record 10153 - already completed
[10/500] Record 10157 - already completed
[11/500] Record 10173 - already completed
[12/500] Record 1024 - already completed
[13/500] Record 10263 - already completed
[14/500] Record 10268 - already completed
[15/500] Record 10295 - already completed
[16/500] Record 10303 - already completed
[17/500] Record 10311 - already completed
[18/500] Record 10312 - already completed
[19/500] Record 10316 - already completed
[20/500] Record 10318 - already completed
[21/500] Record 10319 - already completed
[22/500] Record 10320 - already completed
[23/500] Record 10322 - already completed
[24/500] Record 10445 - already completed
[25/500] Record 11458 - already completed
[26/500] Record 3022 - already completed
[27/500] Record 3533 - already completed
[28/500] Record 3750 - already completed
[29/500] Record 4288 - already completed
[30/500] Record 4292 - already completed
[31/500] Record 4346 - already completed
[32/500] Record 4498 - already completed
[33/500] Record 4706 - already completed
[34/500] Record 490 - already completed
[35/500] Record 4976 - already completed
[36/500] Record 558 - already completed
[37/500] Record 5610 - already completed
[38/500] Record 6071 - already completed
[39/500] Record 6412 - already completed
[40/500] Record 10 - already completed

======================================================================
[41/500] Record ID: 1000
Output: ['Rocky mountain spotted fever', 'typhus fever', 'Q fever', 'rickettsialpox', 'tick fevers caused by Rickettsiae', 'Respiratory tract infections caused by Mycoplasma pneumoniae', 'Lymphogranuloma venereum caused by Chlamydia trachomatis', 'Psittacosis (ornithosis) caused by Chlamydia psittaci', 'Trachoma caused by Chlamydia trachomatis', 'Inclusion conjunctivitis caused by Chlamydia trachomatis', 'Uncomplicated urethral, endocervical or rectal infections in adults caused by Chlamydia trachomatis', 'Nongonococcal urethritis caused by Ureaplasma urealyticum', 'Relapsing fever due to Borrelia recurrentis', 'Chancroid caused by Haemophilus ducreyi', 'Plague due to Yersinia pestis (formerly Pasteurella pestis)', 'Tularemia due to Francisella tularensis (formerly Pasteurella tularensis)', 'Cholera caused by Vibrio cholerae (formerly Vibrio comma)', 'Campylobacter fetus infections caused by Campylobacter fetus (formerly Vibrio fetus)', 'Brucellosis due to Brucella species (in conjunction with streptomycin)', 'Bartonellosis due to Bartonella bacilliformis', 'Granuloma inguinale caused by Calymmatobacterium granulomatis', 'Escherichia coli', 'Enterobacter aerogenes (formerly Aerobacter aerogenes)', 'Shigella species', 'Acinetobacter species (formerly Mima species and Herellea species)', 'Respiratory tract infections caused by Haemophilus influenzae', 'Respiratory tract and urinary tract infections caused by Klebsiella species', 'Streptococcus pneumoniae (formerly Diplococcus pneumoniae)', 'Skin and skin structure infections caused by Staphylococcus aureus', 'Anthrax due to Bacillus anthracis', 'Uncomplicated gonorrhea caused by Neisseria gonorrhoeae', 'Syphilis caused by Treponema pallidum', 'Yaws caused by Treponema pertenue', 'Listeriosis due to Listeria monocytogenes', "Vincent's infection caused by Fusobacterium fusiforme", 'Actinomycosis caused by Actinomyces israelii', 'Infections caused by Clostridium species', 'Acute intestinal amebiasis', 'Severe acne']
Runtime: 37.09 seconds
[42/500] Record 10000 - already completed
[43/500] Record 10003 - already completed
[44/500] Record 10021 - already completed
[45/500] Record 10023 - already completed
[46/500] Record 10029 - already completed
[47/500] Record 10036 - already completed
[48/500] Record 10041 - already completed
[49/500] Record 10043 - already completed
[50/500] Record 10048 - already completed
[51/500] Record 1005 - already completed
[52/500] Record 10054 - already completed
[53/500] Record 10059 - already completed
[54/500] Record 1006 - already completed
[55/500] Record 10072 - already completed
[56/500] Record 10073 - already completed
[57/500] Record 10082 - already completed
[58/500] Record 10084 - already completed
[59/500] Record 10087 - already completed
[60/500] Record 1009 - already completed
[61/500] Record 10090 - already completed
[62/500] Record 10091 - already completed
[63/500] Record 10093 - already completed
[64/500] Record 10096 - already completed
[65/500] Record 10099 - already completed
[66/500] Record 1010 - already completed
[67/500] Record 10109 - already completed
[68/500] Record 1011 - already completed
[69/500] Record 10111 - already completed
[70/500] Record 10113 - already completed
[71/500] Record 10114 - already completed
[72/500] Record 10117 - already completed
[73/500] Record 10119 - already completed
[74/500] Record 1012 - already completed
[75/500] Record 10120 - already completed
[76/500] Record 10127 - already completed
[77/500] Record 10129 - already completed
[78/500] Record 1013 - already completed
[79/500] Record 10132 - already completed
[80/500] Record 1015 - already completed
[81/500] Record 10184 - already completed
[82/500] Record 10185 - already completed
[83/500] Record 10193 - already completed

======================================================================
[84/500] Record ID: 102
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.

======================================================================
[85/500] Record ID: 10205
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.
[86/500] Record 10218 - already completed
[87/500] Record 10291 - already completed
[88/500] Record 10749 - already completed
[89/500] Record 10829 - already completed
[90/500] Record 11018 - already completed
[91/500] Record 1104 - already completed
[92/500] Record 11157 - already completed
[93/500] Record 11274 - already completed
[94/500] Record 11384 - already completed
[95/500] Record 1143 - already completed
[96/500] Record 1147 - already completed
[97/500] Record 11592 - already completed
[98/500] Record 11823 - already completed
[99/500] Record 11961 - already completed
[100/500] Record 12007 - already completed
[101/500] Record 13132 - already completed
[102/500] Record 13886 - already completed
[103/500] Record 13930 - already completed
[104/500] Record 13990 - already completed
[105/500] Record 14125 - already completed
[106/500] Record 14589 - already completed
[107/500] Record 14612 - already completed
[108/500] Record 14779 - already completed
[109/500] Record 15074 - already completed
[110/500] Record 15382 - already completed
[111/500] Record 15439 - already completed
[112/500] Record 1549 - already completed
[113/500] Record 16679 - already completed
[114/500] Record 17240 - already completed
[115/500] Record 2434 - already completed
[116/500] Record 2455 - already completed
[117/500] Record 2553 - already completed
[118/500] Record 2647 - already completed
[119/500] Record 2891 - already completed
[120/500] Record 3205 - already completed
[121/500] Record 3465 - already completed
[122/500] Record 5091 - already completed
[123/500] Record 6536 - already completed
[124/500] Record 7068 - already completed
[125/500] Record 7092 - already completed
[126/500] Record 7157 - already completed
[127/500] Record 7305 - already completed

======================================================================
[128/500] Record ID: 7349
Attempt 1/3 failed: Expecting ',' delimiter: line 1 column 3208 (char 3207)
Attempt 2/3 failed: No JSON object found in model response.
Output: ['Type 2 diabetes mellitus', 'Non-insulin dependent diabetes mellitus', 'Hyperglycemia', 'Obesity', 'Hyperlipidemia', 'Hypertension', 'Diabetic ketoacidosis', 'Diabetic retinopathy', 'Diabetic nephropathy', 'Diabetic neuropathy']
Runtime: 2.47 seconds
[129/500] Record 7703 - already completed
[130/500] Record 9004 - already completed
[131/500] Record 979 - already completed
[132/500] Record 9909 - already completed
[133/500] Record 1079 - already completed
[134/500] Record 11008 - already completed
[135/500] Record 11423 - already completed
[136/500] Record 11646 - already completed
[137/500] Record 11848 - already completed
[138/500] Record 12067 - already completed
[139/500] Record 12749 - already completed
[140/500] Record 13092 - already completed
[141/500] Record 1340 - already completed
[142/500] Record 13857 - already completed
[143/500] Record 15473 - already completed
[144/500] Record 17090 - already completed
[145/500] Record 17331 - already completed
[146/500] Record 18297 - already completed
[147/500] Record 1992 - already completed
[148/500] Record 2231 - already completed
[149/500] Record 236 - already completed
[150/500] Record 2540 - already completed
[151/500] Record 2588 - already completed
[152/500] Record 3113 - already completed
[153/500] Record 3255 - already completed
[154/500] Record 3574 - already completed
[155/500] Record 3606 - already completed
[156/500] Record 374 - already completed
[157/500] Record 4576 - already completed
[158/500] Record 4867 - already completed
[159/500] Record 5060 - already completed
[160/500] Record 5257 - already completed
[161/500] Record 7526 - already completed
[162/500] Record 8370 - already completed
[163/500] Record 9076 - already completed
[164/500] Record 9246 - already completed
[165/500] Record 9588 - already completed
[166/500] Record 10228 - already completed
[167/500] Record 10390 - already completed
[168/500] Record 10462 - already completed
[169/500] Record 1048 - already completed
[170/500] Record 10506 - already completed
[171/500] Record 10604 - already completed
[172/500] Record 11278 - already completed
[173/500] Record 1164 - already completed
[174/500] Record 11924 - already completed
[175/500] Record 12121 - already completed
[176/500] Record 12644 - already completed
[177/500] Record 12730 - already completed
[178/500] Record 12934 - already completed
[179/500] Record 132 - already completed
[180/500] Record 13623 - already completed
[181/500] Record 1373 - already completed
[182/500] Record 145 - already completed
[183/500] Record 14735 - already completed
[184/500] Record 14759 - already completed
[185/500] Record 1478 - already completed
[186/500] Record 14816 - already completed
[187/500] Record 15882 - already completed
[188/500] Record 15933 - already completed
[189/500] Record 16246 - already completed
[190/500] Record 16555 - already completed
[191/500] Record 16791 - already completed
[192/500] Record 17305 - already completed
[193/500] Record 1749 - already completed
[194/500] Record 1835 - already completed
[195/500] Record 1935 - already completed
[196/500] Record 2391 - already completed
[197/500] Record 2492 - already completed
[198/500] Record 3193 - already completed
[199/500] Record 3215 - already completed
[200/500] Record 3438 - already completed
[201/500] Record 4152 - already completed
[202/500] Record 458 - already completed
[203/500] Record 5493 - already completed
[204/500] Record 5639 - already completed
[205/500] Record 6511 - already completed
[206/500] Record 6613 - already completed
[207/500] Record 8496 - already completed
[208/500] Record 8621 - already completed
[209/500] Record 9247 - already completed
[210/500] Record 9295 - already completed
[211/500] Record 9537 - already completed
[212/500] Record 10024 - already completed
[213/500] Record 10368 - already completed
[214/500] Record 10467 - already completed
[215/500] Record 10533 - already completed
[216/500] Record 10545 - already completed
[217/500] Record 11106 - already completed
[218/500] Record 12395 - already completed
[219/500] Record 12599 - already completed
[220/500] Record 12741 - already completed
[221/500] Record 12975 - already completed
[222/500] Record 13128 - already completed
[223/500] Record 13143 - already completed
[224/500] Record 13804 - already completed
[225/500] Record 14259 - already completed
[226/500] Record 1432 - already completed
[227/500] Record 14464 - already completed
[228/500] Record 14670 - already completed
[229/500] Record 14938 - already completed
[230/500] Record 15144 - already completed
[231/500] Record 15626 - already completed
[232/500] Record 15635 - already completed
[233/500] Record 16477 - already completed
[234/500] Record 16611 - already completed
[235/500] Record 16676 - already completed

======================================================================
[236/500] Record ID: 17348
Attempt 1/3 failed: Expecting ',' delimiter: line 1 column 257 (char 256)
Attempt 2/3 failed: Expecting ',' delimiter: line 1 column 257 (char 256)
Attempt 3/3 failed: Expecting ',' delimiter: line 1 column 257 (char 256)
[237/500] Record 2074 - already completed
[238/500] Record 282 - already completed
[239/500] Record 2969 - already completed
[240/500] Record 3059 - already completed
[241/500] Record 3823 - already completed
[242/500] Record 3937 - already completed
[243/500] Record 4270 - already completed
[244/500] Record 6001 - already completed
[245/500] Record 6490 - already completed
[246/500] Record 6875 - already completed
[247/500] Record 8673 - already completed
[248/500] Record 8841 - already completed
[249/500] Record 9473 - already completed
[250/500] Record 993 - already completed
[251/500] Record 10165 - already completed
[252/500] Record 10388 - already completed
[253/500] Record 10554 - already completed
[254/500] Record 10638 - already completed
[255/500] Record 10657 - already completed
[256/500] Record 1081 - already completed
[257/500] Record 1115 - already completed
[258/500] Record 11335 - already completed

======================================================================
[259/500] Record ID: 12261
Output: ['Allergic states', 'Dermatologic diseases', 'Endocrine disorders', 'Gastrointestinal diseases', 'Hematologic disorders', 'Miscellaneous', 'Neoplastic diseases', 'Nervous system', 'Ophthalmic diseases', 'Renal diseases', 'Respiratory diseases', 'Rheumatic disorders']
Runtime: 2.94 seconds
[260/500] Record 12420 - already completed

======================================================================
[261/500] Record ID: 12504
Output: ['Obesity', 'Obesity, severe', 'Obesity, morbid', 'Obesity, severe, with BMI >= 30 kg/m^2']
Runtime: 1.68 seconds
[262/500] Record 1272 - already completed
[263/500] Record 12788 - already completed
[264/500] Record 13923 - already completed
[265/500] Record 14024 - already completed
[266/500] Record 1428 - already completed
[267/500] Record 14566 - already completed
[268/500] Record 14968 - already completed
[269/500] Record 15569 - already completed

======================================================================
[270/500] Record ID: 15627
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.
[271/500] Record 15842 - already completed
[272/500] Record 16308 - already completed
[273/500] Record 16417 - already completed
[274/500] Record 16677 - already completed
[275/500] Record 17086 - already completed
[276/500] Record 18062 - already completed
[277/500] Record 1825 - already completed
[278/500] Record 18353 - already completed
[279/500] Record 2096 - already completed
[280/500] Record 2627 - already completed
[281/500] Record 3129 - already completed
[282/500] Record 3142 - already completed
[283/500] Record 3365 - already completed

======================================================================
[284/500] Record ID: 4354
Attempt 1/3 failed: Extra data: line 3 column 1 (char 42)
Output: ['Coronary artery disease']
Runtime: 4.25 seconds
[285/500] Record 4798 - already completed
[286/500] Record 640 - already completed
[287/500] Record 6611 - already completed
[288/500] Record 7108 - already completed
[289/500] Record 7610 - already completed
[290/500] Record 8091 - already completed
[291/500] Record 8400 - already completed
[292/500] Record 8691 - already completed
[293/500] Record 8742 - already completed
[294/500] Record 8838 - already completed
[295/500] Record 9385 - already completed
[296/500] Record 9410 - already completed
[297/500] Record 9459 - already completed
[298/500] Record 10415 - already completed
[299/500] Record 10615 - already completed
[300/500] Record 10939 - already completed
[301/500] Record 11094 - already completed
[302/500] Record 1111 - already completed
[303/500] Record 11190 - already completed
[304/500] Record 11318 - already completed
[305/500] Record 11642 - already completed
[306/500] Record 11716 - already completed
[307/500] Record 11806 - already completed
[308/500] Record 12018 - already completed
[309/500] Record 12074 - already completed
[310/500] Record 12572 - already completed
[311/500] Record 12834 - already completed
[312/500] Record 12915 - already completed

======================================================================
[313/500] Record ID: 13123
Output: ['Hypercholesterolemia', 'Hyperlipidemia', 'Hypertriglyceridemia', 'Dysproteinemias', 'Obstructive liver disease', 'Other drug therapy', 'Alcoholism', 'Type IIb hyperlipidemia', 'Type IIa hyperlipidemia', 'Type IV hyperlipidemia', 'Type V hyperlipidemia', 'Type III hyperlipidemia', 'Homozygous familial hypercholesterolemia', 'Heterozygous familial hypercholesterolemia', 'CHD', 'Peripheral vessel disease', 'History of stroke or other cerebrovascular disease', 'Diabetes', 'Fredrickson types IIa and IIb hyperlipidemia', 'Fredrickson type lV hyperlipidemia', 'Fredrickson type lll hyperlipidemia', 'Adolescent patients with Heterozygous Familial Hypercholesterolemia (HeFH)']
Runtime: 7.91 seconds

======================================================================
[314/500] Record ID: 14232
Attempt 1/3 failed: No JSON object found in model response.
Attempt 2/3 failed: No JSON object found in model response.
Attempt 3/3 failed: No JSON object found in model response.
[315/500] Record 1495 - already completed
[316/500] Record 15258 - already completed
[317/500] Record 15583 - already completed
[318/500] Record 15884 - already completed
[319/500] Record 1644 - already completed
[320/500] Record 16651 - already completed
[321/500] Record 16793 - already completed
[322/500] Record 17291 - already completed
[323/500] Record 17407 - already completed
[324/500] Record 2049 - already completed
[325/500] Record 225 - already completed
[326/500] Record 2843 - already completed
[327/500] Record 2900 - already completed
[328/500] Record 3128 - already completed
[329/500] Record 3287 - already completed
[330/500] Record 3481 - already completed
[331/500] Record 3702 - already completed
[332/500] Record 3833 - already completed
[333/500] Record 4013 - already completed
[334/500] Record 5212 - already completed
[335/500] Record 7075 - already completed
[336/500] Record 7536 - already completed
[337/500] Record 7917 - already completed
[338/500] Record 7950 - already completed
[339/500] Record 8595 - already completed
[340/500] Record 9041 - already completed
[341/500] Record 10252 - already completed
[342/500] Record 10352 - already completed
[343/500] Record 10361 - already completed
[344/500] Record 10482 - already completed
[345/500] Record 10489 - already completed
[346/500] Record 10933 - already completed
[347/500] Record 10934 - already completed
[348/500] Record 11759 - already completed
[349/500] Record 11779 - already completed
[350/500] Record 1185 - already completed

In [ ]:
print(df["openbiollm_status"].value_counts(dropna=False))

openbiollm_status
OK          468
OK_EMPTY     24
FAILED        8
Name: count, dtype: int64

In [ ]:
failed_rows = df[
    df["openbiollm_status"] == "FAILED"
]

display(
    failed_rows[
        [
            "record_id",
            "gold_expert_mentions",
            "openbiollm_raw"
        ]
    ]
)

,record_id,gold_expert_mentions,openbiollm_raw
83,102,coronary heart disease; myocardial infarction;...,No JSON object found in model response.
84,10205,coronary heart disease; myocardial infarction;...,No JSON object found in model response.
235,17348,hypertension; Edema; congestive heart failure;...,"Expecting ',' delimiter: line 1 column 257 (ch..."
269,15627,hypertension,No JSON object found in model response.
313,14232,Allergic Rhinitis; seasonal and perennial alle...,No JSON object found in model response.
418,4722,hyperthyroidism; toxic multinodular goiter,No JSON object found in model response.
425,10518,Graves disease; hyperthyroidism; toxic multino...,Extra data: line 3 column 1 (char 33)
497,4060,gout,No JSON object found in model response.

In [ ]:
def extract_openbiollm_raw(indication_text):

    user_message = EXTRACTION_TEMPLATE.format(
        indication_text=indication_text
    )

    prompt = (
        "<|begin_of_text|>"
        "<|start_header_id|>system<|end_header_id|>\n\n"
        + SYSTEM_MESSAGE
        + "<|eot_id|>"
        "<|start_header_id|>user<|end_header_id|>\n\n"
        + user_message
        + "<|eot_id|>"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
    )

    payload = {
        "model": MODEL,
        "prompt": prompt,
        "raw": True,
        "stream": False,
        "options": {
            "temperature": 0.1,
            "num_ctx": 4096,
            "num_predict": 1000,
            "stop": [
                "<|eot_id|>",
                "<|end_of_text|>"
            ]
        }
    }

    start_time = time.time()

    response = requests.post(
        URL,
        json=payload,
        timeout=240
    )

    response.raise_for_status()

    raw_output = response.json()["response"]

    runtime = round(
        time.time() - start_time,
        2
    )

    return raw_output, runtime

In [ ]:
def parse_output_robust(raw_output):

    raw_output = raw_output.strip()

    # Remove Markdown code fences if present
    raw_output = raw_output.replace("```json", "")
    raw_output = raw_output.replace("```", "")
    raw_output = raw_output.strip()

    decoder = json.JSONDecoder()

    # ------------------------------------------------
    # Try ordinary JSON
    # ------------------------------------------------
    try:
        parsed = json.loads(raw_output)

    except json.JSONDecodeError:

        # --------------------------------------------
        # Find beginning of JSON object
        # --------------------------------------------
        start = raw_output.find("{")

        if start == -1:
            raise ValueError(
                "No JSON object found in model response."
            )

        # raw_decode reads the first valid JSON object
        # and ignores text appearing afterward
        parsed, end_position = decoder.raw_decode(
            raw_output[start:]
        )

    if "diseases" not in parsed:
        raise ValueError(
            "JSON does not contain 'diseases'."
        )

    diseases = parsed["diseases"]

    if not isinstance(diseases, list):
        raise ValueError(
            "'diseases' must be a list."
        )

    cleaned = []
    seen = set()

    for disease in diseases:

        if not isinstance(disease, str):
            continue

        disease = disease.strip()

        if not disease:
            continue

        key = disease.lower()

        if key not in seen:
            seen.add(key)
            cleaned.append(disease)

    return cleaned

In [ ]:
failed_indices = df.index[
    df["openbiollm_status"] == "FAILED"
].tolist()

print(
    "Failed records to retry:",
    len(failed_indices)
)


for i in failed_indices:

    record_id = df.at[i, "record_id"]
    indication_text = str(
        df.at[i, "indication_text"]
    )

    print()
    print("=" * 70)
    print("Record ID:", record_id)

    try:

        # Get actual model response FIRST
        raw, runtime = extract_openbiollm_raw(
            indication_text
        )

        # Always save the actual response
        df.at[i, "openbiollm_raw"] = raw
        df.at[i, "openbiollm_runtime_sec"] = runtime

        print()
        print("RAW MODEL RESPONSE:")
        print(raw)

        # Now try parsing
        diseases = parse_output_robust(raw)

        df.at[i, "openbiollm_output"] = json.dumps(
            diseases,
            ensure_ascii=False
        )

        df.at[i, "openbiollm_status"] = (
            "OK"
            if diseases
            else "OK_EMPTY"
        )

        print()
        print("PARSED:")
        print(diseases)

    except Exception as e:

        df.at[i, "openbiollm_status"] = "FAILED"

        print()
        print("PARSING FAILED:")
        print(e)


# Save immediately
df.to_excel(
    RESULT_FILE,
    index=False
)

print()
print("Updated results saved.")

Failed records to retry: 8

======================================================================
Record ID: 102

RAW MODEL RESPONSE:
{"diseases":["hypercholesterolemia","hyperlipidemia","type 2 diabetes","coronary heart disease","atherosclerotic vascular disease","mixed dyslipidemia","dysbetalipoproteinemia","homozygous familial hypercholesterolemia","heterozygous familial hypercholesterolemia","type 3 hyperlipidemia","type 4 hyperlipidemia","type 5 hyperlipidemia","type 6 hyperlipidemia","type 7 hyperlipidemia","type 8 hyperlipidemia","type 9 hyperlipidemia","type 10 hyperlipidemia","type 11 hyperlipidemia","type 12 hyperlipidemia","type 13 hyperlipidemia","type 14 hyperlipidemia","type 15 hyperlipidemia","type 16 hyperlipidemia","type 17 hyperlipidemia","type 18 hyperlipidemia","type 19 hyperlipidemia","type 20 hyperlipidemia","type 21 hyperlipidemia","type 22 hyperlipidemia","type 23 hyperlipidemia","type 24 hyperlipidemia","type 25 hyperlipidemia","type 26 hyperlipidemia","type 27 hyperlipidemia","type 28 hyperlipidemia","type 29 hyperlipidemia","type 30 hyperlipidemia","type 31 hyperlipidemia","type 32 hyperlipidemia","type 33 hyperlipidemia","type 34 hyperlipidemia","type 35 hyperlipidemia","type 36 hyperlipidemia","type 37 hyperlipidemia","type 38 hyperlipidemia","type 39 hyperlipidemia","type 40 hyperlipidemia","type 41 hyperlipidemia","type 42 hyperlipidemia","type 43 hyperlipidemia","type 44 hyperlipidemia","type 45 hyperlipidemia","type 46 hyperlipidemia","type 47 hyperlipidemia","type 48 hyperlipidemia","type 49 hyperlipidemia","type 50 hyperlipidemia","type 51 hyperlipidemia","type 52 hyperlipidemia","type 53 hyperlipidemia","type 54 hyperlipidemia","type 55 hyperlipidemia","type 56 hyperlipidemia","type 57 hyperlipidemia","type 58 hyperlipidemia","type 59 hyperlipidemia","type 60 hyperlipidemia","type 61 hyperlipidemia","type 62 hyperlipidemia","type 63 hyperlipidemia","type 64 hyperlipidemia","type 65 hyperlipidemia","type 66 hyperlipidemia","type 67 hyperlipidemia","type 68 hyperlipidemia","type 69 hyperlipidemia","type 70 hyperlipidemia","type 71 hyperlipidemia","type 72 hyperlipidemia","type 73 hyperlipidemia","type 74 hyperlipidemia","type 75 hyperlipidemia","type 76 hyperlipidemia","type 77 hyperlipidemia","type 78 hyperlipidemia","type 79 hyperlipidemia","type 80 hyperlipidemia","type 81 hyperlipidemia","type 82 hyperlipidemia","type 83 hyperlipidemia","type 84 hyperlipidemia","type 85 hyperlipidemia","type 86 hyperlipidemia","type 87 hyperlipidemia","type 88 hyperlipidemia","type 89 hyperlipidemia","type 90 hyperlipidemia","type 91 hyperlipidemia","type 92 hyperlipidemia","type 93 hyperlipidemia","type 94 hyperlipidemia","type 95 hyperlipidemia","type 96 hyperlipidemia","type 97 hyperlipidemia","type 98 hyperlipidemia","type 99 hyperlipidemia","type 100 hyperlipidemia","type 101 hyperlipidemia","type 102 hyperlipidemia","type 103 hyperlipidemia","type 104 hyperlipidemia","type 105 hyperlipidemia","type 106 hyperlipidemia","type 107 hyperlipidemia","type 108 hyperlipidemia","type 109 hyperlipidemia","type 110 hyperlipidemia","type 111 hyperlipidemia","type 112 hyperlipidemia","type 113 hyperlipidemia","type 114 hyperlipidemia","type 115 hyperlipidemia","type 116 hyperlipidemia","type 117 hyperlipidemia","type 118 hyper

PARSING FAILED:
Unterminated string starting at: line 1 column 3152 (char 3151)

======================================================================
Record ID: 10205

RAW MODEL RESPONSE:
{"diseases":["Hypercholesterolemia","Hyperlipidemia","Type IIa Hyperlipidemia","Type IIb Hyperlipidemia","Type III Hyperlipidemia","Type IV Hyperlipidemia","Familial Hypercholesterolemia","Type IIa Dyslipidemia","Type IIb Dyslipidemia","Type III Dyslipidemia","Type IV Dyslipidemia","Type V Dyslipidemia","Type VI Dyslipidemia","Type VII Dyslipidemia","Type VIII Dyslipidemia","Type IX Dyslipidemia","Type X Dyslipidemia","Type XI Dyslipidemia","Type XII Dyslipidemia","Type XIII Dyslipidemia","Type XIV Dyslipidemia","Type XV Dyslipidemia","Type XVI Dyslipidemia","Type XVII Dyslipidemia","Type XVIII Dyslipidemia","Type XIX Dyslipidemia","Type XX Dyslipidemia","Type XXI Dyslipidemia","Type XXII Dyslipidemia","Type XXIII Dyslipidemia","Type XXIV Dyslipidemia","Type XXV Dyslipidemia","Type XXVI Dyslipidemia","Type XXVII Dyslipidemia","Type XXVIII Dyslipidemia","Type XXIX Dyslipidemia","Type XXX Dyslipidemia","Type XXXI Dyslipidemia","Type XXXII Dyslipidemia","Type XXXIII Dyslipidemia","Type XXXIV Dyslipidemia","Type XXXV Dyslipidemia","Type XXXVI Dyslipidemia","Type XXXVII Dyslipidemia","Type XXXVIII Dyslipidemia","Type XXXIX Dyslipidemia","Type XL Dyslipidemia","Type XLI Dyslipidemia","Type XLII Dyslipidemia","Type XLIII Dyslipidemia","Type XLIV Dyslipidemia","Type XLV Dyslipidemia","Type XLVI Dyslipidemia","Type XLVII Dyslipidemia","Type XLVIII Dyslipidemia","Type XLIX Dyslipidemia","Type L Dyslipidemia","Type LI Dyslipidemia","Type LII Dyslipidemia","Type LIII Dyslipidemia","Type LIV Dyslipidemia","Type LV Dyslipidemia","Type LVI Dyslipidemia","Type LVII Dyslipidemia","Type LVIII Dyslipidemia","Type LIX Dyslipidemia","Type LX Dyslipidemia","Type LXI Dyslipidemia","Type LXII Dyslipidemia","Type LXIII Dyslipidemia","Type LXIV Dyslipidemia","Type LXV Dyslipidemia","Type LXVI Dyslipidemia","Type LXVII Dyslipidemia","Type LXVIII Dyslipidemia","Type LXIX Dyslipidemia","Type LXX Dyslipidemia","Type LXXI Dyslipidemia","Type LXXII Dyslipidemia","Type LXXIII Dyslipidemia","Type LXXIV Dyslipidemia","Type LXXV Dyslipidemia","Type LXXVI Dyslipidemia","Type LXXVII Dyslipidemia","Type LXXVIII Dyslipidemia","Type LXXIX Dyslipidemia","Type LXXX Dyslipidemia","Type LXXXI Dyslipidemia","Type LXXXII Dyslipidemia","Type LXXXIII Dyslipidemia","Type LXXXIV Dyslipidemia","Type LXXXV Dyslipidemia","Type LXXXVI Dyslipidemia","Type LXXXVII Dyslipidemia","Type LXXXVIII Dyslipidemia","Type LXXXIX Dyslipidemia","Type XC Dyslipidemia","Type XCI Dyslipidemia","Type XCII Dyslipidemia","Type XCIII Dyslipidemia","Type XCIV Dyslipidemia","Type XCV Dyslipidemia","Type XCVI Dyslipidemia","Type XCVII Dyslipidemia","Type XCVIII Dyslipidemia","Type XCIX Dyslipidemia","Type C Dyslipidemia","Type CI Dyslipidemia","Type CII Dyslipidemia","Type CIII Dyslipidemia","Type CIV Dyslipidemia","Type CV Dyslipidemia","Type CVI Dyslipidemia","Type CVII Dyslipidemia","Type CVIII Dyslipidemia","Type CIX Dyslipidemia","Type CX Dyslipidemia","Type CXI Dyslipidemia","Type CXII Dyslipidemia","Type CXIII Dyslipidemia","Type CXIV Dyslipidemia","Type CXV Dyslipidemia","Type CXVI Dyslipidemia","Type CXVII Dyslipidemia

PARSING FAILED:
Unterminated string starting at: line 1 column 3083 (char 3082)

======================================================================
Record ID: 17348

RAW MODEL RESPONSE:
{"diseases":["hypertension","congestive heart failure","hepatic cirrhosis","nephrotic syndrome","acute glomerulonephritis","chronic renal failure","toxemia of pregnancy","generalized edema due to pathologic causes","dependent edema due to restriction of venous return by the expanded uterus","edema associated with hepatic cirrhosis","edema associated with congestive heart failure","edema associated with corticosteroid and estrogen therapy","edema due to various forms of renal dysfunction","edema due to nephrotic syndrome","edema due to acute glomerulonephritis","edema due to chronic renal failure","edema due to pathologic causes","toxemia of pregnancy","generalized edema due to pathologic causes","dependent edema due to restriction of venous return by the expanded uterus","edema associated with hepatic cirrhosis","edema associated with congestive heart failure","edema associated with corticosteroid and estrogen therapy","edema due to various forms of renal dysfunction","edema due to nephrotic syndrome","edema due to acute glomerulonephritis","edema due to chronic renal failure","edema due to pathologic causes","toxemia of pregnancy"}

PARSING FAILED:
Expecting ',' delimiter: line 1 column 1150 (char 1149)

======================================================================
Record ID: 15627

RAW MODEL RESPONSE:
1.2 hypertension Tekturna is indicated for the treatment of hypertension , to lower blood pressure. Lowering blood pressure reduces the risk of fatal and nonfatal cardiovascular events, primarily strokes and myocardial infarctions. These benefits have been seen in controlled trials of antihypertensive drugs from a wide variety of pharmacologic classes. There are no controlled trials demonstrating risk reduction with Tekturna. Control of high blood pressure should be part of comprehensive cardiovascular risk management, including, as appropriate, lipid control, diabetes management, antithrombotic therapy, smoking cessation, exercise, and limited sodium intake. Many patients will require more than one drug to achieve blood pressure goals. For specific advice on goals and management, see published guidelines, such as those of the National High Blood Pressure Education Program s Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (JNC). Numerous antihypertensive drugs, from a variety of pharmacologic classes and with different mechanisms of action, have been shown in randomized controlled trials to reduce cardiovascular morbidity and mortality, and it can be concluded that it is blood pressure reduction, and not some other pharmacologic property of the drugs, that is largely responsible for those benefits. The largest and most consistent cardiovascular outcome benefit has been a reduction in the risk of stroke, but reductions in myocardial infarction and cardiovascular mortality also have been seen regularly. Elevated systolic or diastolic pressure causes increased cardiovascular risk, and the absolute risk increase per mmHg is greater at higher blood pressures, so that even modest reductions of severe hypertension can provide substantial benefit. Relative risk reduction from blood pressure reduction is similar across populations with varying absolute risk, so the absolute benefit is greater in patients who are at higher risk independent of their hypertension (for example, patients with diabetes or hyperlipidemia), and such patients would be expected to benefit from more aggressive treatment to a lower blood pressure goal. Some antihypertensive drugs have smaller blood pressure effects (as monotherapy) in black patients, and many antihypertensive drugs have additional approved indications and effects (e.g., on angina, heart failure, or diabetic kidney disease). These considerations may guide selection of therapy.şivitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitch

PARSING FAILED:
No JSON object found in model response.

======================================================================
Record ID: 14232

RAW MODEL RESPONSE:
1.2 Treatment of Asthma VERAMYST (fluticasone furoate) Inhalation Powder is indicated for the prophylactic treatment of mild to moderate asthma in patients aged 4 years and older. It is not indicated for the immediate relief of acute asthma symptoms.

PARSING FAILED:
No JSON object found in model response.

======================================================================
Record ID: 4722

RAW MODEL RESPONSE:
{"diseases":["Graves disease"]}

Methimazole is also indicated for the treatment of hyperthyroidism due to a thyroid nodule or adenoma, as well as for the treatment of metastatic, anaplastic, or follicular thyroid cancer. It is also used in the management of McCune-Albright syndrome, which is characterized by a triad of café-au-lait spots, fibrous dysplasia, and polyostotic fibrous dysplasia.

PARSED:
['Graves disease']

======================================================================
Record ID: 10518

RAW MODEL RESPONSE:
{"diseases":["Graves disease"]}

{"diseases":[]}

PARSED:
['Graves disease']

======================================================================
Record ID: 4060

RAW MODEL RESPONSE:
Colchicine is indicated for the treatment of familial Mediterranean fever (FMF) in adults and children 4 years of age and older.workitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitch

PARSING FAILED:
No JSON object found in model response.

Updated results saved.

In [ ]:
print(
    df["openbiollm_status"]
    .value_counts(dropna=False)
)

openbiollm_status
OK          470
OK_EMPTY     24
FAILED        6
Name: count, dtype: int64

In [ ]:
remaining_failed = df[
    df["openbiollm_status"] == "FAILED"
]

display(
    remaining_failed[
        [
            "record_id",
            "gold_expert_mentions",
            "openbiollm_raw"
        ]
    ]
)

,record_id,gold_expert_mentions,openbiollm_raw
83,102,coronary heart disease; myocardial infarction;...,"{""diseases"":[""hypercholesterolemia"",""hyperlipi..."
84,10205,coronary heart disease; myocardial infarction;...,"{""diseases"":[""Hypercholesterolemia"",""Hyperlipi..."
235,17348,hypertension; Edema; congestive heart failure;...,"{""diseases"":[""hypertension"",""congestive heart ..."
269,15627,hypertension,1.2 hypertension Tekturna is indicated for the...
313,14232,Allergic Rhinitis; seasonal and perennial alle...,1.2 Treatment of Asthma VERAMYST (fluticasone ...
497,4060,gout,Colchicine is indicated for the treatment of f...

In [ ]:
failed = df[df["openbiollm_status"] == "FAILED"]

for i, row in failed.iterrows():

    print("=" * 80)
    print("ROW:", i)
    print("RECORD ID:", row["record_id"])
    print()
    print("RAW RESPONSE:")
    print(repr(row["openbiollm_raw"]))
    print()

================================================================================
ROW: 83
RECORD ID: 102

RAW RESPONSE:
'{"diseases":["hypercholesterolemia","hyperlipidemia","type 2 diabetes","coronary heart disease","atherosclerotic vascular disease","mixed dyslipidemia","dysbetalipoproteinemia","homozygous familial hypercholesterolemia","heterozygous familial hypercholesterolemia","type 3 hyperlipidemia","type 4 hyperlipidemia","type 5 hyperlipidemia","type 6 hyperlipidemia","type 7 hyperlipidemia","type 8 hyperlipidemia","type 9 hyperlipidemia","type 10 hyperlipidemia","type 11 hyperlipidemia","type 12 hyperlipidemia","type 13 hyperlipidemia","type 14 hyperlipidemia","type 15 hyperlipidemia","type 16 hyperlipidemia","type 17 hyperlipidemia","type 18 hyperlipidemia","type 19 hyperlipidemia","type 20 hyperlipidemia","type 21 hyperlipidemia","type 22 hyperlipidemia","type 23 hyperlipidemia","type 24 hyperlipidemia","type 25 hyperlipidemia","type 26 hyperlipidemia","type 27 hyperlipidemia","type 28 hyperlipidemia","type 29 hyperlipidemia","type 30 hyperlipidemia","type 31 hyperlipidemia","type 32 hyperlipidemia","type 33 hyperlipidemia","type 34 hyperlipidemia","type 35 hyperlipidemia","type 36 hyperlipidemia","type 37 hyperlipidemia","type 38 hyperlipidemia","type 39 hyperlipidemia","type 40 hyperlipidemia","type 41 hyperlipidemia","type 42 hyperlipidemia","type 43 hyperlipidemia","type 44 hyperlipidemia","type 45 hyperlipidemia","type 46 hyperlipidemia","type 47 hyperlipidemia","type 48 hyperlipidemia","type 49 hyperlipidemia","type 50 hyperlipidemia","type 51 hyperlipidemia","type 52 hyperlipidemia","type 53 hyperlipidemia","type 54 hyperlipidemia","type 55 hyperlipidemia","type 56 hyperlipidemia","type 57 hyperlipidemia","type 58 hyperlipidemia","type 59 hyperlipidemia","type 60 hyperlipidemia","type 61 hyperlipidemia","type 62 hyperlipidemia","type 63 hyperlipidemia","type 64 hyperlipidemia","type 65 hyperlipidemia","type 66 hyperlipidemia","type 67 hyperlipidemia","type 68 hyperlipidemia","type 69 hyperlipidemia","type 70 hyperlipidemia","type 71 hyperlipidemia","type 72 hyperlipidemia","type 73 hyperlipidemia","type 74 hyperlipidemia","type 75 hyperlipidemia","type 76 hyperlipidemia","type 77 hyperlipidemia","type 78 hyperlipidemia","type 79 hyperlipidemia","type 80 hyperlipidemia","type 81 hyperlipidemia","type 82 hyperlipidemia","type 83 hyperlipidemia","type 84 hyperlipidemia","type 85 hyperlipidemia","type 86 hyperlipidemia","type 87 hyperlipidemia","type 88 hyperlipidemia","type 89 hyperlipidemia","type 90 hyperlipidemia","type 91 hyperlipidemia","type 92 hyperlipidemia","type 93 hyperlipidemia","type 94 hyperlipidemia","type 95 hyperlipidemia","type 96 hyperlipidemia","type 97 hyperlipidemia","type 98 hyperlipidemia","type 99 hyperlipidemia","type 100 hyperlipidemia","type 101 hyperlipidemia","type 102 hyperlipidemia","type 103 hyperlipidemia","type 104 hyperlipidemia","type 105 hyperlipidemia","type 106 hyperlipidemia","type 107 hyperlipidemia","type 108 hyperlipidemia","type 109 hyperlipidemia","type 110 hyperlipidemia","type 111 hyperlipidemia","type 112 hyperlipidemia","type 113 hyperlipidemia","type 114 hyperlipidemia","type 115 hyperlipidemia","type 116 hyperlipidemia","type 117 hyperlipidemia","type 118 hyper'

================================================================================
ROW: 84
RECORD ID: 10205

RAW RESPONSE:
'{"diseases":["Hypercholesterolemia","Hyperlipidemia","Type IIa Hyperlipidemia","Type IIb Hyperlipidemia","Type III Hyperlipidemia","Type IV Hyperlipidemia","Familial Hypercholesterolemia","Type IIa Dyslipidemia","Type IIb Dyslipidemia","Type III Dyslipidemia","Type IV Dyslipidemia","Type V Dyslipidemia","Type VI Dyslipidemia","Type VII Dyslipidemia","Type VIII Dyslipidemia","Type IX Dyslipidemia","Type X Dyslipidemia","Type XI Dyslipidemia","Type XII Dyslipidemia","Type XIII Dyslipidemia","Type XIV Dyslipidemia","Type XV Dyslipidemia","Type XVI Dyslipidemia","Type XVII Dyslipidemia","Type XVIII Dyslipidemia","Type XIX Dyslipidemia","Type XX Dyslipidemia","Type XXI Dyslipidemia","Type XXII Dyslipidemia","Type XXIII Dyslipidemia","Type XXIV Dyslipidemia","Type XXV Dyslipidemia","Type XXVI Dyslipidemia","Type XXVII Dyslipidemia","Type XXVIII Dyslipidemia","Type XXIX Dyslipidemia","Type XXX Dyslipidemia","Type XXXI Dyslipidemia","Type XXXII Dyslipidemia","Type XXXIII Dyslipidemia","Type XXXIV Dyslipidemia","Type XXXV Dyslipidemia","Type XXXVI Dyslipidemia","Type XXXVII Dyslipidemia","Type XXXVIII Dyslipidemia","Type XXXIX Dyslipidemia","Type XL Dyslipidemia","Type XLI Dyslipidemia","Type XLII Dyslipidemia","Type XLIII Dyslipidemia","Type XLIV Dyslipidemia","Type XLV Dyslipidemia","Type XLVI Dyslipidemia","Type XLVII Dyslipidemia","Type XLVIII Dyslipidemia","Type XLIX Dyslipidemia","Type L Dyslipidemia","Type LI Dyslipidemia","Type LII Dyslipidemia","Type LIII Dyslipidemia","Type LIV Dyslipidemia","Type LV Dyslipidemia","Type LVI Dyslipidemia","Type LVII Dyslipidemia","Type LVIII Dyslipidemia","Type LIX Dyslipidemia","Type LX Dyslipidemia","Type LXI Dyslipidemia","Type LXII Dyslipidemia","Type LXIII Dyslipidemia","Type LXIV Dyslipidemia","Type LXV Dyslipidemia","Type LXVI Dyslipidemia","Type LXVII Dyslipidemia","Type LXVIII Dyslipidemia","Type LXIX Dyslipidemia","Type LXX Dyslipidemia","Type LXXI Dyslipidemia","Type LXXII Dyslipidemia","Type LXXIII Dyslipidemia","Type LXXIV Dyslipidemia","Type LXXV Dyslipidemia","Type LXXVI Dyslipidemia","Type LXXVII Dyslipidemia","Type LXXVIII Dyslipidemia","Type LXXIX Dyslipidemia","Type LXXX Dyslipidemia","Type LXXXI Dyslipidemia","Type LXXXII Dyslipidemia","Type LXXXIII Dyslipidemia","Type LXXXIV Dyslipidemia","Type LXXXV Dyslipidemia","Type LXXXVI Dyslipidemia","Type LXXXVII Dyslipidemia","Type LXXXVIII Dyslipidemia","Type LXXXIX Dyslipidemia","Type XC Dyslipidemia","Type XCI Dyslipidemia","Type XCII Dyslipidemia","Type XCIII Dyslipidemia","Type XCIV Dyslipidemia","Type XCV Dyslipidemia","Type XCVI Dyslipidemia","Type XCVII Dyslipidemia","Type XCVIII Dyslipidemia","Type XCIX Dyslipidemia","Type C Dyslipidemia","Type CI Dyslipidemia","Type CII Dyslipidemia","Type CIII Dyslipidemia","Type CIV Dyslipidemia","Type CV Dyslipidemia","Type CVI Dyslipidemia","Type CVII Dyslipidemia","Type CVIII Dyslipidemia","Type CIX Dyslipidemia","Type CX Dyslipidemia","Type CXI Dyslipidemia","Type CXII Dyslipidemia","Type CXIII Dyslipidemia","Type CXIV Dyslipidemia","Type CXV Dyslipidemia","Type CXVI Dyslipidemia","Type CXVII Dyslipidemia'

================================================================================
ROW: 235
RECORD ID: 17348

RAW RESPONSE:
'{"diseases":["hypertension","congestive heart failure","hepatic cirrhosis","nephrotic syndrome","acute glomerulonephritis","chronic renal failure","toxemia of pregnancy","generalized edema due to pathologic causes","dependent edema due to restriction of venous return by the expanded uterus","edema associated with hepatic cirrhosis","edema associated with congestive heart failure","edema associated with corticosteroid and estrogen therapy","edema due to various forms of renal dysfunction","edema due to nephrotic syndrome","edema due to acute glomerulonephritis","edema due to chronic renal failure","edema due to pathologic causes","toxemia of pregnancy","generalized edema due to pathologic causes","dependent edema due to restriction of venous return by the expanded uterus","edema associated with hepatic cirrhosis","edema associated with congestive heart failure","edema associated with corticosteroid and estrogen therapy","edema due to various forms of renal dysfunction","edema due to nephrotic syndrome","edema due to acute glomerulonephritis","edema due to chronic renal failure","edema due to pathologic causes","toxemia of pregnancy"}'

================================================================================
ROW: 269
RECORD ID: 15627

RAW RESPONSE:
'1.2 hypertension Tekturna is indicated for the treatment of hypertension , to lower blood pressure. Lowering blood pressure reduces the risk of fatal and nonfatal cardiovascular events, primarily strokes and myocardial infarctions. These benefits have been seen in controlled trials of antihypertensive drugs from a wide variety of pharmacologic classes. There are no controlled trials demonstrating risk reduction with Tekturna. Control of high blood pressure should be part of comprehensive cardiovascular risk management, including, as appropriate, lipid control, diabetes management, antithrombotic therapy, smoking cessation, exercise, and limited sodium intake. Many patients will require more than one drug to achieve blood pressure goals. For specific advice on goals and management, see published guidelines, such as those of the National High Blood Pressure Education Program s Joint National Committee on Prevention, Detection, Evaluation, and Treatment of High Blood Pressure (JNC). Numerous antihypertensive drugs, from a variety of pharmacologic classes and with different mechanisms of action, have been shown in randomized controlled trials to reduce cardiovascular morbidity and mortality, and it can be concluded that it is blood pressure reduction, and not some other pharmacologic property of the drugs, that is largely responsible for those benefits. The largest and most consistent cardiovascular outcome benefit has been a reduction in the risk of stroke, but reductions in myocardial infarction and cardiovascular mortality also have been seen regularly. Elevated systolic or diastolic pressure causes increased cardiovascular risk, and the absolute risk increase per mmHg is greater at higher blood pressures, so that even modest reductions of severe hypertension can provide substantial benefit. Relative risk reduction from blood pressure reduction is similar across populations with varying absolute risk, so the absolute benefit is greater in patients who are at higher risk independent of their hypertension (for example, patients with diabetes or hyperlipidemia), and such patients would be expected to benefit from more aggressive treatment to a lower blood pressure goal. Some antihypertensive drugs have smaller blood pressure effects (as monotherapy) in black patients, and many antihypertensive drugs have additional approved indications and effects (e.g., on angina, heart failure, or diabetic kidney disease). These considerations may guide selection of therapy.şivitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitch'

================================================================================
ROW: 313
RECORD ID: 14232

RAW RESPONSE:
'1.2 Treatment of Asthma VERAMYST (fluticasone furoate) Inhalation Powder is indicated for the prophylactic treatment of mild to moderate asthma in patients aged 4 years and older. It is not indicated for the immediate relief of acute asthma symptoms.'

================================================================================
ROW: 497
RECORD ID: 4060

RAW RESPONSE:
'Colchicine is indicated for the treatment of familial Mediterranean fever (FMF) in adults and children 4 years of age and older.workitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitchitch'

In [ ]:
!pip -q install json-repair

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 5.2 MB/s eta 0:00:00

In [ ]:
from json_repair import repair_json
import json


# -------------------------------------------------------
# Only repair record 17348 because its intended JSON
# output is present but syntactically malformed.
# -------------------------------------------------------

idx = df.index[
    df["record_id"] == 17348
][0]

raw = df.at[idx, "openbiollm_raw"]

try:

    repaired = repair_json(raw)

    parsed = json.loads(repaired)

    diseases = parsed["diseases"]

    # Remove duplicates while preserving order
    cleaned = []
    seen = set()

    for disease in diseases:

        disease = str(disease).strip()

        if disease and disease.lower() not in seen:

            seen.add(disease.lower())
            cleaned.append(disease)

    df.at[idx, "openbiollm_output"] = json.dumps(
        cleaned,
        ensure_ascii=False
    )

    df.at[idx, "openbiollm_status"] = "OK_REPAIRED"

    print("Record 17348 repaired:")
    print(cleaned)

except Exception as e:

    print("Repair failed:", e)

Record 17348 repaired:
['hypertension', 'congestive heart failure', 'hepatic cirrhosis', 'nephrotic syndrome', 'acute glomerulonephritis', 'chronic renal failure', 'toxemia of pregnancy', 'generalized edema due to pathologic causes', 'dependent edema due to restriction of venous return by the expanded uterus', 'edema associated with hepatic cirrhosis', 'edema associated with congestive heart failure', 'edema associated with corticosteroid and estrogen therapy', 'edema due to various forms of renal dysfunction', 'edema due to nephrotic syndrome', 'edema due to acute glomerulonephritis', 'edema due to chronic renal failure', 'edema due to pathologic causes']

In [ ]:
format_failed_ids = [
    102,
    10205,
    15627,
    14232,
    4060
]

for record_id in format_failed_ids:

    idx = df.index[
        df["record_id"] == record_id
    ][0]

    df.at[
        idx,
        "openbiollm_status"
    ] = "FORMAT_FAILED"

    # No usable structured prediction
    df.at[
        idx,
        "openbiollm_output"
    ] = "[]"

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("Saved:", RESULT_FILE)

Saved: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_OpenBioLLM_Results.xlsx

In [ ]:
print(
    df["openbiollm_status"]
    .value_counts(dropna=False)
)

openbiollm_status
OK               470
OK_EMPTY          24
FORMAT_FAILED      5
OK_REPAIRED        1
Name: count, dtype: int64

In [ ]:
failed_indices = df.index[
    df["openbiollm_status"] == "FAILED"
]

for i in failed_indices:

    df.at[i, "openbiollm_status"] = "FORMAT_FAILED"

    # No usable structured prediction
    df.at[i, "openbiollm_output"] = "[]"

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("Saved:", RESULT_FILE)

Saved: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_OpenBioLLM_Results.xlsx

In [ ]:
print(
    df["openbiollm_status"]
    .value_counts(dropna=False)
)

openbiollm_status
OK               470
OK_EMPTY          24
FORMAT_FAILED      5
OK_REPAIRED        1
Name: count, dtype: int64

In [ ]:
!ollama stop koesn/llama3-openbiollm-8b:q5_K_M