In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!nvidia-smi

Sat Sep 26 04:21:42 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/LLMValidation_LabeledIn")

INPUT_FILE = BASE_DIR / "LabeledIn_LLM_Benchmark.xlsx"

RESULT_FILE = BASE_DIR / "LabeledIn_Qwen3_8B_Results.xlsx"

print("BASE_DIR:", BASE_DIR)
print("Benchmark exists:", INPUT_FILE.exists())
print("Result file:", RESULT_FILE)

BASE_DIR: /content/drive/MyDrive/LLMValidation_LabeledIn
Benchmark exists: True
Result file: /content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Qwen3_8B_Results.xlsx

In [ ]:
!pip -q install pandas openpyxl requests json-repair

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 3.7 MB/s eta 0:00:00

In [ ]:
!apt-get update -qq
!apt-get install -y zstd

W: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 81 not upgraded.
Need to get 644 kB of archives.
After this operation, 1,845 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 zstd amd64 1.5.5+dfsg2-2build1.1 [644 kB]
Fetched 644 kB in 1s (521 kB/s)
Selecting previously unselected package zstd.
(Reading database ... 126952 files and directories currently installed.)
Preparing to unpack .../zstd_1.5.5+dfsg2-2build1.1_amd64.deb ...
Unpacking zstd (1.5.5+dfsg2-2build1.1) ...
Setting up zstd (1.5.5+dfsg2-2build1.1) ...
Processing triggers for man-db (2.12.0-4build2) ...

In [ ]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
!ollama --version

Warning: could not connect to a running Ollama instance
Warning: client version is 0.34.0

In [ ]:
import subprocess
import time

ollama_process = subprocess.Popen(
    ["ollama", "serve"],
    stdout=open("/content/ollama.log", "w"),
    stderr=subprocess.STDOUT
)

time.sleep(5)

print("Ollama server started.")

Ollama server started.

In [ ]:
import requests

response = requests.get(
    "http://127.0.0.1:11434/api/tags",
    timeout=10
)

print("Status code:", response.status_code)
print(response.json())

Status code: 200
{'models': []}

In [ ]:
!ollama list

NAME    ID    SIZE    MODIFIED

In [ ]:
!ollama pull qwen3:8b

In [ ]:
!ollama list

NAME        ID              SIZE      MODIFIED
qwen3:8b    500a1f067a9f    5.2 GB    35 seconds ago

In [ ]:
import requests
import json

payload = {
    "model": "qwen3:8b",
    "messages": [
        {
            "role": "user",
            "content": "Return only JSON: {\"diseases\":[\"hypertension\"]}"
        }
    ],
    "stream": False,
    "think": False
}

response = requests.post(
    "http://127.0.0.1:11434/api/chat",
    json=payload,
    timeout=240
)

print(response.json()["message"]["content"])

{"diseases":["hypertension"]}

In [ ]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/LLMValidation_LabeledIn")

INPUT_FILE = BASE_DIR / "LabeledIn_LLM_Benchmark.xlsx"
RESULT_FILE = BASE_DIR / "LabeledIn_Qwen3_8B_Results.xlsx"

df = pd.read_excel(
    INPUT_FILE,
    sheet_name="Benchmark"
)

print("Number of records:", len(df))
print("Columns:")
print(df.columns.tolist())

assert len(df) == 500, (
    f"Expected 500 records but found {len(df)}"
)

print("✓ Full 500-record benchmark loaded successfully.")

Number of records: 500
Columns:
['record_id', 'dailymed_setid', 'indication_text', 'gold_expert_mentions', 'gold_umls_cuis', 'gold_cui_mention_pairs', 'gold_unique_mention_count', 'gold_unique_cui_count', 'annotation_occurrence_count', 'word_count', 'related_setid_count', 'gold_source', 'openbiollm_output', 'openbiollm_status', 'pubmed_output', 'pubmed_status', 'gemma_output', 'gemma_status', 'medgemma_output', 'medgemma_status']
✓ Full 500-record benchmark loaded successfully.

In [ ]:
display(
    df[
        [
            "record_id",
            "indication_text",
            "gold_expert_mentions",
            "gold_umls_cuis"
        ]
    ].head()
)

,record_id,indication_text,gold_expert_mentions,gold_umls_cuis
0,10004,Pantoprazole sodium delayed release tablets ar...,Erosive Esophagitis; Gastroesophageal Reflux D...,C0267055; C0017168; C0043515
1,10008,Anxiety Disorders Alprazolam tablets are indic...,Anxiety Disorders; anxiety disorder; Anxiety; ...,C0003469; C0338908; C0030319; C0001818
2,10012,Amiodarone hydrochloride injection is indicate...,ventricular fibrillation; ventricular tachycar...,C0042510; C0042514
3,10016,"Clobetasol propionate foam, 0.05% is a super p...",dermatoses; plaque type psoriasis,C0037274; C0406317
4,10017,Metaxalone tablets are indicated as an adjunct...,"acute, painful",C0184567

In [ ]:
for column in [
    "qwen3_output",
    "qwen3_raw",
    "qwen3_status",
    "qwen3_runtime_sec"
]:
    if column not in df.columns:
        df[column] = ""

print("Qwen result columns created.")

Qwen result columns created.

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("Initial Qwen result file saved:")
print(RESULT_FILE)

Initial Qwen result file saved:
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Qwen3_8B_Results.xlsx

In [ ]:
import json
import time
import requests

MODEL = "qwen3:8b"

URL = "http://127.0.0.1:11434/api/chat"

SYSTEM_MESSAGE = """
You are a biomedical information extraction system.
Follow the user's extraction instructions exactly.
Return only the requested JSON output.
""".strip()

EXTRACTION_TEMPLATE = """
Extract ALL diseases, disorders, syndromes, symptoms, or clinical conditions
for which the drug is explicitly indicated in the following
Indications and Usage text.

Rules:

1. Read the entire supplied text.
2. Include every explicitly stated clinical indication.
3. Include symptoms or clinical conditions when explicitly indicated
   for treatment, prevention, management, or relief.
4. Preserve clinically meaningful disease subtypes and modifiers.
5. Use wording from the supplied text as closely as possible.
6. Do not intentionally normalize or generalize disease names.
7. Do not infer conditions that are not explicitly supported by the text.
8. Exclude conditions explicitly stated as NOT indicated or NOT recommended.
9. Exclude causative organisms when they merely describe the cause of infection.
10. Exclude mechanisms, procedures, dosing information,
    treatment regimens, and patient demographics.
11. Remove duplicate clinical conditions.

Return ONLY valid JSON:

{{"diseases":["condition 1","condition 2"]}}

If there are genuinely no indications:

{{"diseases":[]}}

INDICATIONS AND USAGE:

{indication_text}
""".strip()

In [ ]:
def parse_output(raw_output):

    raw_output = str(raw_output).strip()

    # Remove Markdown code fences if Qwen adds them
    raw_output = raw_output.replace("```json", "")
    raw_output = raw_output.replace("```", "")
    raw_output = raw_output.strip()

    try:
        parsed = json.loads(raw_output)

    except json.JSONDecodeError:

        start = raw_output.find("{")
        end = raw_output.rfind("}")

        if start == -1 or end == -1 or end < start:
            raise ValueError(
                "No JSON object found in model response."
            )

        parsed = json.loads(
            raw_output[start:end + 1]
        )

    if "diseases" not in parsed:
        raise ValueError(
            "JSON does not contain 'diseases'."
        )

    diseases = parsed["diseases"]

    if not isinstance(diseases, list):
        raise ValueError(
            "'diseases' must be a list."
        )

    cleaned = []
    seen = set()

    for disease in diseases:

        if not isinstance(disease, str):
            continue

        disease = disease.strip()

        if not disease:
            continue

        key = disease.lower()

        if key not in seen:
            seen.add(key)
            cleaned.append(disease)

    return cleaned

In [ ]:
def extract_qwen3(indication_text):

    user_message = EXTRACTION_TEMPLATE.format(
        indication_text=indication_text
    )

    payload = {
        "model": MODEL,

        "messages": [
            {
                "role": "system",
                "content": SYSTEM_MESSAGE
            },
            {
                "role": "user",
                "content": user_message
            }
        ],

        "stream": False,

        # Disable reasoning output
        "think": False,

        "options": {
            "temperature": 0.1,
            "num_ctx": 4096,
            "num_predict": 1000
        }
    }

    start_time = time.time()

    response = requests.post(
        URL,
        json=payload,
        timeout=240
    )

    response.raise_for_status()

    result = response.json()

    raw_output = result["message"]["content"]

    diseases = parse_output(raw_output)

    runtime = round(
        time.time() - start_time,
        2
    )

    return diseases, raw_output, runtime

In [ ]:
test_text = """
Metoprolol is indicated for the treatment of
hypertension and angina pectoris.
"""

diseases, raw, runtime = extract_qwen3(test_text)

print("RAW OUTPUT:")
print(raw)

print("\nPARSED OUTPUT:")
print(diseases)

print("\nRuntime:", runtime, "seconds")

RAW OUTPUT:
{"diseases":["hypertension","angina pectoris"]}

PARSED OUTPUT:
['hypertension', 'angina pectoris']

Runtime: 0.96 seconds

In [ ]:
test_text = """
Metoprolol is indicated for the treatment of
hypertension and angina pectoris.
"""

diseases, raw, runtime = extract_qwen3(test_text)

print("RAW OUTPUT:")
print(raw)

print("\nPARSED OUTPUT:")
print(diseases)

print("\nRuntime:", runtime, "seconds")

RAW OUTPUT:
{"diseases":["hypertension","angina pectoris"]}

PARSED OUTPUT:
['hypertension', 'angina pectoris']

Runtime: 0.64 seconds

In [ ]:
for i in range(5):

    record_id = df.loc[i, "record_id"]

    indication_text = str(
        df.loc[i, "indication_text"]
    )

    print()
    print("=" * 80)
    print(f"RECORD {i + 1}/5")
    print("Record ID:", record_id)

    print("\nGOLD:")
    print(
        df.loc[i, "gold_expert_mentions"]
    )

    try:

        diseases, raw, runtime = extract_qwen3(
            indication_text
        )

        df.at[
            i,
            "qwen3_output"
        ] = json.dumps(
            diseases,
            ensure_ascii=False
        )

        df.at[
            i,
            "qwen3_raw"
        ] = raw

        df.at[
            i,
            "qwen3_status"
        ] = (
            "OK"
            if diseases
            else "OK_EMPTY"
        )

        df.at[
            i,
            "qwen3_runtime_sec"
        ] = runtime

        print("\nQWEN OUTPUT:")
        print(diseases)

        print(
            "\nRuntime:",
            runtime,
            "seconds"
        )

    except Exception as e:

        df.at[
            i,
            "qwen3_status"
        ] = "FAILED"

        df.at[
            i,
            "qwen3_raw"
        ] = str(e)

        print("\nERROR:")
        print(e)

================================================================================
RECORD 1/5
Record ID: 10004

GOLD:
Erosive Esophagitis; Gastroesophageal Reflux Disease; GERD; Zollinger Ellison Syndrome

QWEN OUTPUT:
['Erosive Esophagitis Associated With Gastroesophageal Reflux Disease ( GERD )', 'Erosive Esophagitis', 'Maintenance of Healing of Erosive Esophagitis', 'Pathological Hypersecretory Conditions Including Zollinger Ellison Syndrome']

Runtime: 2.83 seconds

================================================================================
RECORD 2/5
Record ID: 10008

GOLD:
Anxiety Disorders; anxiety disorder; Anxiety; Anxiety associated with depression; Panic Disorder; agoraphobia

QWEN OUTPUT:
['anxiety disorder', 'Panic Disorder']

Runtime: 1.31 seconds

================================================================================
RECORD 3/5
Record ID: 10012

GOLD:
ventricular fibrillation; ventricular tachycardia; VT; VF

QWEN OUTPUT:
['ventricular fibrillation', 'hemodynamically unstable ventricular tachycardia', 'VT VF']

Runtime: 1.35 seconds

================================================================================
RECORD 4/5
Record ID: 10016

GOLD:
dermatoses; plaque type psoriasis

QWEN OUTPUT:
['inflammatory and pruritic manifestations of moderate to severe corticosteroid responsive dermatoses of the scalp', 'mild to moderate plaque type psoriasis on non scalp regions excluding the face and intertriginous areas']

Runtime: 2.29 seconds

================================================================================
RECORD 5/5
Record ID: 10017

GOLD:
acute, painful

QWEN OUTPUT:
['acute, painful musculoskeletal conditions']

Runtime: 0.65 seconds

In [ ]:
display(
    df[
        [
            "record_id",
            "gold_expert_mentions",
            "qwen3_output",
            "qwen3_status",
            "qwen3_runtime_sec"
        ]
    ].head(5)
)

,record_id,gold_expert_mentions,qwen3_output,qwen3_status,qwen3_runtime_sec
0,10004,Erosive Esophagitis; Gastroesophageal Reflux D...,"[""Erosive Esophagitis Associated With Gastroes...",OK,2.83
1,10008,Anxiety Disorders; anxiety disorder; Anxiety; ...,"[""anxiety disorder"", ""Panic Disorder""]",OK,1.31
2,10012,ventricular fibrillation; ventricular tachycar...,"[""ventricular fibrillation"", ""hemodynamically ...",OK,1.35
3,10016,dermatoses; plaque type psoriasis,"[""inflammatory and pruritic manifestations of ...",OK,2.29
4,10017,"acute, painful","[""acute, painful musculoskeletal conditions""]",OK,0.65

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("Saved:")
print(RESULT_FILE)

Saved:
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Qwen3_8B_Results.xlsx

In [ ]:
def run_all_qwen3():

    total = len(df)

    assert total == 500, (
        f"Expected 500 records but found {total}"
    )

    print("=" * 80)
    print("QWEN3 8B — FULL LABELEDIN RUN")
    print("Total records:", total)
    print("=" * 80)

    for i in range(total):

        record_id = df.loc[
            i,
            "record_id"
        ]

        current_status = str(
            df.at[
                i,
                "qwen3_status"
            ]
        ).strip()

        # Skip already completed records
        if current_status in [
            "OK",
            "OK_EMPTY",
            "OK_REPAIRED"
        ]:

            print(
                f"[{i + 1}/{total}] "
                f"Record {record_id} "
                "- already completed"
            )

            continue

        indication_text = str(
            df.loc[
                i,
                "indication_text"
            ]
        )

        print()
        print("=" * 80)

        print(
            f"[{i + 1}/{total}] "
            f"Record ID: {record_id}"
        )

        success = False
        last_error = ""

        # Try maximum 3 times
        for attempt in range(1, 4):

            try:

                diseases, raw, runtime = extract_qwen3(
                    indication_text
                )

                df.at[
                    i,
                    "qwen3_output"
                ] = json.dumps(
                    diseases,
                    ensure_ascii=False
                )

                df.at[
                    i,
                    "qwen3_raw"
                ] = raw

                df.at[
                    i,
                    "qwen3_status"
                ] = (
                    "OK"
                    if diseases
                    else "OK_EMPTY"
                )

                df.at[
                    i,
                    "qwen3_runtime_sec"
                ] = runtime

                print(
                    "Output:",
                    diseases
                )

                print(
                    "Runtime:",
                    runtime,
                    "seconds"
                )

                success = True
                break

            except Exception as e:

                last_error = str(e)

                print(
                    f"Attempt {attempt}/3 failed:",
                    e
                )

                time.sleep(2)

        if not success:

            df.at[
                i,
                "qwen3_status"
            ] = "FAILED"

            df.at[
                i,
                "qwen3_raw"
            ] = last_error

        # Save checkpoint every 20 records
        if (
            (i + 1) % 20 == 0
            or
            i == total - 1
        ):

            df.to_excel(
                RESULT_FILE,
                index=False
            )

            print(
                "\n>>> CHECKPOINT SAVED TO GOOGLE DRIVE"
            )

    # Final save
    df.to_excel(
        RESULT_FILE,
        index=False
    )

    print()
    print("=" * 80)
    print("QWEN3 8B FINISHED")
    print("=" * 80)

    print("Saved to:")
    print(RESULT_FILE)

In [ ]:
run_all_qwen3()

================================================================================
QWEN3 8B — FULL LABELEDIN RUN
Total records: 500
================================================================================
[1/500] Record 10004 - already completed
[2/500] Record 10008 - already completed
[3/500] Record 10012 - already completed
[4/500] Record 10016 - already completed
[5/500] Record 10017 - already completed

================================================================================
[6/500] Record ID: 1001
Output: ['Hypertension', 'Angina Pectoris', 'hemodynamically stable patients with definite or suspected acute myocardial infarction']
Runtime: 1.62 seconds

================================================================================
[7/500] Record ID: 10140
Output: ['major depressive disorder']
Runtime: 0.76 seconds

================================================================================
[8/500] Record ID: 10146
Output: ['insomnia']
Runtime: 0.51 seconds

================================================================================
[9/500] Record ID: 10153
Output: ['anxiety and tension associated with psychoneurosis', 'pruritus due to allergic conditions such as chronic urticaria and atopic and contact dermatoses', 'histamine mediated pruritus']
Runtime: 2.17 seconds

================================================================================
[10/500] Record ID: 10157
Output: ["Parkinson's disease", "idiopathic Parkinson's disease"]
Runtime: 0.92 seconds

================================================================================
[11/500] Record ID: 10173
Output: ['partial onset seizures', 'myoclonic seizures', 'primary generalized tonic clonic seizures']
Runtime: 1.1 seconds

================================================================================
[12/500] Record ID: 1024
Output: ['head lice infestations']
Runtime: 0.65 seconds

================================================================================
[13/500] Record ID: 10263
Output: ['LOWER RESPIRATORY TRACT INFECTIONS', 'ACUTE BACTERIAL OTITIS MEDIA', 'SKIN AND SKIN STRUCTURE INFECTIONS', 'URINARY TRACT INFECTIONS (complicated and uncomplicated)', 'UNCOMPLICATED GONORRHEA (cervical urethral and rectal)', 'PELLVIC INFLAMMATORY DISEASE', 'BACTERIAL SEPTICEMIA', 'BONE AND JOINT INFECTIONS', 'INTRA ABDOMINAL INFECTIONS', 'MENINGITIS', 'SURGICAL PROPHYLAXIS']
Runtime: 7.07 seconds

================================================================================
[14/500] Record ID: 10268
Output: ['Essential hypertension']
Runtime: 0.64 seconds

================================================================================
[15/500] Record ID: 10295
Output: ['megaloblastic anemias due to a deficiency of folic acid', 'tropical or nontropical sprue', 'anemias of nutritional origin', 'pregnancy', 'infancy', 'childhood']
Runtime: 2.32 seconds

================================================================================
[16/500] Record ID: 10303
Output: ['symptomatic benign prostatic hyperplasia ( BPH )']
Runtime: 1.0 seconds

================================================================================
[17/500] Record ID: 10311
Output: ['venous thrombosis', 'pulmonary embolism ( PE )', 'thromboembolic complications associated with atrial fibrillation ( AF ) and/or cardiac valve replacement', 'risk of death, recurrent myocardial infarction ( MI ), and thromboembolic events such as stroke or systemic embolization after myocardial infarction']
Runtime: 3.89 seconds

================================================================================
[18/500] Record ID: 10312
Output: ['type 2 diabetes mellitus']
Runtime: 0.78 seconds

================================================================================
[19/500] Record ID: 10316
Output: ['Benign Prostatic Hyperplasia ( BPH )', 'Hypertension']
Runtime: 1.41 seconds

================================================================================
[20/500] Record ID: 10318
Output: ['the inflammatory and pruritic manifestations of corticosteroid responsive dermatoses', 'moderate to severe plaque type psoriasis']
Runtime: 1.84 seconds

>>> CHECKPOINT SAVED TO GOOGLE DRIVE

================================================================================
[21/500] Record ID: 10319
Output: ['nausea and vomiting associated with highly emetogenic cancer chemotherapy', 'nausea and vomiting associated with initial and repeat courses of moderately emetogenic cancer chemotherapy', 'nausea and vomiting associated with radiotherapy', 'postoperative nausea and/or vomiting']
Runtime: 3.05 seconds

================================================================================
[22/500] Record ID: 10320
Output: ['intermittent claudication']
Runtime: 0.69 seconds

================================================================================
[23/500] Record ID: 10322
Output: ['hyperkalemia']
Runtime: 0.58 seconds

================================================================================
[24/500] Record ID: 10445
Output: ['cough']
Runtime: 0.49 seconds

================================================================================
[25/500] Record ID: 11458
Output: ['Major Depressive Disorder', 'Seasonal Affective Disorder']
Runtime: 1.46 seconds

================================================================================
[26/500] Record ID: 3022
Output: ['asthma']
Runtime: 0.89 seconds

================================================================================
[27/500] Record ID: 3533
Output: ['motion sickness', 'nausea and vomiting associated with motion sickness', 'nausea and vomiting associated with recovery from anesthesia and surgery']
Runtime: 2.03 seconds

================================================================================
[28/500] Record ID: 3750
Output: ['Schizophrenia']
Runtime: 0.77 seconds

================================================================================
[29/500] Record ID: 4288
Output: ['pulmonary arterial hypertension (WHO Group I)']
Runtime: 1.35 seconds

================================================================================
[30/500] Record ID: 4292
Output: ['rejection in renal homotransplantation', 'active Rheumatoid Arthritis']
Runtime: 2.08 seconds

================================================================================
[31/500] Record ID: 4346
Output: ['gestational choriocarcinoma', 'chorioadenoma destruens', 'hydatidiform mole', 'acute lymphocytic leukemia', 'meningeal leukemia', 'breast cancer', 'epidermoid cancers of the head and neck', 'advanced mycosis fungoides ( cutaneous T cell lymphoma )', 'lung cancer', 'non Hodgkin s lymphomas', 'non metastatic osteosarcoma', 'Psoriasis', 'Rheumatoid Arthritis', 'Polyarticular Course Juvenile Rheumatoid Arthritis']
Runtime: 10.07 seconds

================================================================================
[32/500] Record ID: 4498
Output: ['overactive bladder with symptoms of urge urinary incontinence, urgency, and frequency']
Runtime: 1.38 seconds

================================================================================
[33/500] Record ID: 4706
Output: ['reversible obstructive airway disease']
Runtime: 0.77 seconds

================================================================================
[34/500] Record ID: 490
Output: ['Attention Deficit Disorders', 'Narcolepsy', 'Attention Deficit Disorders (previously known as Minimal Brain Dysfunction in Children)', 'Hyperkinetic Child Syndrome', 'Minimal Brain Damage', 'Minimal Cerebral Dysfunction', 'Minor Cerebral Dysfunction', 'behavioral syndrome characterized by the following group of developmentally inappropriate symptoms moderate to severe distractibility, short attention span, hyperactivity, emotional lability, and impulsivity']
Runtime: 4.84 seconds

================================================================================
[35/500] Record ID: 4976
Output: ['Primary hypogonadism (congenital or acquired)', 'testicular failure due to conditions such as cryptorchidism, bilateral torsion, orchitis, vanishing testis syndrome, orchiectomy, Klinefelter Syndrome , chemotherapy, or toxic damage from alcohol or heavy metals', 'Hypogonadotropic hypogondeism (congenital or acquired)', 'idiopathic gonadotropin or luteinizing hormone releasing hormone (LHRH) deficiency or pituitary hypothalamic injury from tumors, trauma, or radiation']
Runtime: 6.19 seconds

================================================================================
[36/500] Record ID: 558
Output: ['hypertension']
Runtime: 0.59 seconds

================================================================================
[37/500] Record ID: 5610
Output: ['hypertension', 'angina']
Runtime: 0.62 seconds

================================================================================
[38/500] Record ID: 6071
Output: ['Restless Legs Syndrome', 'Postherpetic Neuralgia']
Runtime: 0.94 seconds

================================================================================
[39/500] Record ID: 6412
Output: ['moderate to severe pain not responsive to non narcotic analgesics', 'opioid addiction (heroin or other morphine like drugs)']
Runtime: 2.41 seconds

================================================================================
[40/500] Record ID: 10
Output: ['hypertension']
Runtime: 0.51 seconds

>>> CHECKPOINT SAVED TO GOOGLE DRIVE

================================================================================
[41/500] Record ID: 1000
Output: ['Rocky mountain spotted fever', 'typhus fever and the typhus group', 'Q fever', 'rickettsialpox', 'tick fevers caused by Rickettsiae', 'Respiratory tract infections caused by Mycoplasma pneumoniae', 'Lymphogranuloma venereum caused by Chlamydia trachomatis', 'Psittacosis (ornithosis) caused by Chlamydia psittaci', 'Trachoma caused by Chlamydia trachomatis', 'Inclusion conjunctivitis caused by Chlamydia trachomatis', 'Uncomplicated urethral, endocervical or rectal infections in adults caused by Chlamydia trachomatis', 'Nongonococcal urethritis caused by Ureaplasma urealyticum', 'Relapsing fever due to Borrelia recurrentis', 'Chancroid caused by Haemophilus ducreyi', 'Plague due to Yersinia pestis', 'Tularemia due to Francisella tularensis', 'Cholera caused by Vibrio cholerae', 'Campylobacter fetus infections caused by Campylobacter fetus', 'Brucellosis due to Brucella species', 'Bartonellosis due to Bartonella bacilliformis', 'Granuloma inguinale caused by Calymmatobacterium granulomatis', 'Escherichia coli', 'Enterobacter aerogenes', 'Shigella species', 'Acinetobacter species', 'Respiratory tract infections caused by Haemophilus influenzae', 'Respiratory tract and urinary tract infections caused by Klebsiella species', 'Upper respiratory infections caused by Streptococcus pneumoniae', 'Skin and skin structure infections caused by Staphylococcus aureus', 'Anthrax due to Bacillus anthracis', 'Uncomplicated gonorrhea caused by Neisseria gonorrhoeae', 'Syphilis caused by Treponema pallidum', 'Yaws caused by Treponema pertenue', 'Listeriosis due to Listeria monocytogenes', "Vincent's infection caused by Fusobacterium fusiforme", 'Actinomycosis caused by Actinomyces israelii', 'Infections caused by Clostridium species', 'acute intestinal amebiasis', 'severe acne']
Runtime: 23.42 seconds

================================================================================
[42/500] Record ID: 10000
Output: ['depression']
Runtime: 0.66 seconds

================================================================================
[43/500] Record ID: 10003
Output: ['Epilepsy', 'Partial seizures with complex symptomatology (psychomotor, temporal lobe)', 'Generalized tonic clonic seizures (grand mal)', 'Mixed seizure patterns which include the above, or other partial or generalized seizures', 'Trigeminal Neuralgia', 'glossopharyngeal neuralgia']
Runtime: 3.27 seconds

================================================================================
[44/500] Record ID: 10021
Output: ['Left Ventricular Dysfunction Following Myocardial Infarction', 'Hypertension']
Runtime: 1.3 seconds

================================================================================
[45/500] Record ID: 10023
Output: ['inflammatory lesions of rosacea']
Runtime: 0.63 seconds

================================================================================
[46/500] Record ID: 10029
Output: ['Infections of the ear, nose, and throat', 'Infections of the genitourinary tract', 'Infections of the skin and skin structure', 'Infections of the lower respiratory tract', 'Gonorrhea , acute uncomplicated (ano genital and urethral infections)', 'pylori infection and duodenal ulcer disease (active or 1 year history of a duodenal ulcer )']
Runtime: 5.93 seconds

================================================================================
[47/500] Record ID: 10036
Output: ["Parkinson's Disease", 'Restless Legs Syndrome']
Runtime: 1.1 seconds

================================================================================
[48/500] Record ID: 10041
Output: ['type 2 diabetes mellitus']
Runtime: 0.69 seconds

================================================================================
[49/500] Record ID: 10043
Output: ['Amelioration of allergic reactions to blood or plasma', 'In anaphylaxis as an adjunct to epinephrine and other standard measures after the acute symptoms have been controlled', 'For other uncomplicated allergic conditions of the immediate type when oral therapy is impossible or contraindicated', 'For sedation and relief of apprehension and to produce light sleep from which the patient can be easily aroused', 'Active treatment of motion sickness', 'Prevention and control of nausea and vomiting associated with certain types of anesthesia and surgery', 'As an adjunct to analgesics for the control of postoperative pain', 'Preoperative, postoperative, and obstetric (during labor) sedation', 'Intravenously in special surgical situations, such as repeated bronchoscopy, ophthalmic surgery, and poor risk patients, with reduced amounts of meperidine or other narcotic analgesic as an adjunct to anesthesia and analgesia']
Runtime: 9.65 seconds

================================================================================
[50/500] Record ID: 10048
Output: ['depression']
Runtime: 0.53 seconds

================================================================================
[51/500] Record ID: 1005
Output: ['chronic asthma', 'other chronic lung diseases', 'emphysema', 'chronic bronchitis']
Runtime: 1.35 seconds

================================================================================
[52/500] Record ID: 10054
Output: ['hypertension']
Runtime: 0.55 seconds

================================================================================
[53/500] Record ID: 10059
Output: ['Hypothyroidism', 'congenital hypothyroidism', 'acquired hypothyroidism', 'primary hypothyroidism', 'secondary hypothyroidism', 'tertiary hypothyroidism', 'subclinical hypothyroidism', 'thyroid nodules', 'subacute or chronic lymphocytic thyroiditis', "Hashimoto's thyroiditis", 'multinodular goiter', 'thyrotropin dependent well differentiated thyroid cancer']
Runtime: 4.85 seconds

================================================================================
[54/500] Record ID: 1006
Output: ['type 2 diabetes mellitus']
Runtime: 0.76 seconds

================================================================================
[55/500] Record ID: 10072
Output: ['Attention Deficit Hyperactivity Disorder ( ADHD )']
Runtime: 1.43 seconds

================================================================================
[56/500] Record ID: 10073
Output: ['acute, painful musculoskeletal conditions']
Runtime: 1.05 seconds

================================================================================
[57/500] Record ID: 10082
Output: ['acute bacterial exacerbations of chronic obstructive pulmonary disease', 'acute bacterial sinusitis', 'community acquired pneumonia', 'pharyngitis tonsillitis', 'uncomplicated skin and skin structure infections', 'urethritis and cervicitis', 'genital ulcer disease in men', 'acute otitis media', 'community acquired pneumonia in patients appropriate for oral therapy']
Runtime: 4.92 seconds

================================================================================
[58/500] Record ID: 10084
Output: ['Psychoneurotic patients with Depression and/or anxiety', 'Depression and/or anxiety associated with alcoholism', 'Depression and/or anxiety associated with organic disease', 'Psychotic depressive disorders with associated anxiety including involutional depression and manic depressive disorders', 'anxiety', 'tension', 'Depression', 'somatic symptoms and concerns', 'sleep disturbances', 'guilt', 'lack of energy', 'fear', 'apprehension and worry']
Runtime: 4.82 seconds

================================================================================
[59/500] Record ID: 10087
Output: ['Hypertension', 'Chronic Stable Angina', "Vasospastic Angina (Prinzmetal's or Variant Angina)", 'Angiographically Documented CAD']
Runtime: 2.23 seconds

================================================================================
[60/500] Record ID: 1009
Output: ['Hypertension', 'Hypertension and Left Ventricular Hypertrophy', 'diabetic nephropathy with an elevated serum creatinine and proteinuria (urinary albumin to creatinine ratio 300 mg g)']
Runtime: 2.9 seconds

>>> CHECKPOINT SAVED TO GOOGLE DRIVE

================================================================================
[61/500] Record ID: 10090
Output: ['moderately severe, acute pain that requires analgesia at the opioid level', 'moderately severe acute pain that requires analgesia at the opioid level']
Runtime: 2.44 seconds

================================================================================
[62/500] Record ID: 10091
Output: ['Primary hypogonadism (congenital or acquired) testicular failure due to cryptorchidism, bilateral torsion, orchitis, vanishing testis syndrome; or orchidectomy', 'Hypogonadotropic hypogonadism (congenital or acquired) idiopathic gonadotropin or LHRH deficiency, or pituitary hypothalamic injury from tumors, trauma, or radiation']
Runtime: 4.7 seconds

================================================================================
[63/500] Record ID: 10093
Output: ['very high elevations of serum triglyceride levels (Types IV and V hyperlipidemia)', 'Type V hyperlipidemia', 'Type IV hyperlipidemia', 'Type I hyperlipoproteinemia', 'coronary heart disease', 'hypertriglyceridemia', 'low HDL cholesterol', 'elevated LDL cholesterol', 'elevated triglycerides', 'hypothyroidism', 'diabetes mellitus', 'familial hypertriglyceridemia']
Runtime: 5.72 seconds

================================================================================
[64/500] Record ID: 10096
Output: ['depression', 'major depressive disorder', 'major depressive episode']
Runtime: 1.4 seconds

================================================================================
[65/500] Record ID: 10099
Output: ['depression', 'Major Depressive Episode']
Runtime: 0.93 seconds

================================================================================
[66/500] Record ID: 1010
Output: ['Major Depressive Disorder', 'Generalized Anxiety Disorder']
Runtime: 1.1 seconds

================================================================================
[67/500] Record ID: 10109

In [ ]:
print(
    df["qwen3_status"]
    .value_counts(dropna=False)
)

qwen3_status
OK          499
OK_EMPTY      1
Name: count, dtype: int64

In [ ]:
completed = df[
    df["qwen3_status"].isin(
        [
            "OK",
            "OK_EMPTY",
            "OK_REPAIRED"
        ]
    )
]

failed = df[
    df["qwen3_status"] == "FAILED"
]

print("Total records :", len(df))
print("Completed     :", len(completed))
print("Failed        :", len(failed))

Total records : 500
Completed     : 500
Failed        : 0

In [ ]:
failed_rows = df[
    df["qwen3_status"] == "FAILED"
]

display(
    failed_rows[
        [
            "record_id",
            "gold_expert_mentions",
            "qwen3_raw"
        ]
    ]
)

Empty DataFrame
Columns: [record_id, gold_expert_mentions, qwen3_raw]
Index: []

In [ ]:
failed_rows = df[
    df["qwen3_status"] == "FAILED"
]

display(
    failed_rows[
        [
            "record_id",
            "gold_expert_mentions",
            "qwen3_raw"
        ]
    ]
)

Empty DataFrame
Columns: [record_id, gold_expert_mentions, qwen3_raw]
Index: []

In [ ]:
def parse_output_robust(raw_output):

    raw_output = str(raw_output).strip()

    raw_output = raw_output.replace("```json", "")
    raw_output = raw_output.replace("```", "")
    raw_output = raw_output.strip()

    decoder = json.JSONDecoder()

    try:

        parsed = json.loads(
            raw_output
        )

    except json.JSONDecodeError:

        start = raw_output.find("{")

        if start == -1:
            raise ValueError(
                "No JSON object found."
            )

        parsed, _ = decoder.raw_decode(
            raw_output[start:]
        )

    if "diseases" not in parsed:
        raise ValueError(
            "No diseases field."
        )

    diseases = parsed["diseases"]

    if not isinstance(diseases, list):
        raise ValueError(
            "'diseases' must be a list."
        )

    cleaned = []
    seen = set()

    for disease in diseases:

        if not isinstance(disease, str):
            continue

        disease = disease.strip()

        if not disease:
            continue

        key = disease.lower()

        if key not in seen:

            seen.add(key)
            cleaned.append(disease)

    return cleaned

In [ ]:
failed_indices = df.index[
    df["qwen3_status"] == "FAILED"
].tolist()

print(
    "Failed records to retry:",
    len(failed_indices)
)

for i in failed_indices:

    record_id = df.at[
        i,
        "record_id"
    ]

    indication_text = str(
        df.at[
            i,
            "indication_text"
        ]
    )

    print()
    print("=" * 80)
    print("Retrying:", record_id)

    try:

        user_message = EXTRACTION_TEMPLATE.format(
            indication_text=indication_text
        )

        payload = {
            "model": MODEL,

            "messages": [
                {
                    "role": "system",
                    "content": SYSTEM_MESSAGE
                },
                {
                    "role": "user",
                    "content": user_message
                }
            ],

            "stream": False,
            "think": False,

            "options": {
                "temperature": 0.1,
                "num_ctx": 4096,
                "num_predict": 1000
            }
        }

        start_time = time.time()

        response = requests.post(
            URL,
            json=payload,
            timeout=240
        )

        response.raise_for_status()

        raw = response.json()[
            "message"
        ][
            "content"
        ]

        runtime = round(
            time.time() - start_time,
            2
        )

        diseases = parse_output_robust(
            raw
        )

        df.at[
            i,
            "qwen3_output"
        ] = json.dumps(
            diseases,
            ensure_ascii=False
        )

        df.at[
            i,
            "qwen3_raw"
        ] = raw

        df.at[
            i,
            "qwen3_status"
        ] = (
            "OK"
            if diseases
            else "OK_EMPTY"
        )

        df.at[
            i,
            "qwen3_runtime_sec"
        ] = runtime

        print("Recovered:", diseases)

    except Exception as e:

        print(
            "Still failed:",
            e
        )

df.to_excel(
    RESULT_FILE,
    index=False
)

print("Retry results saved.")

Failed records to retry: 0
Retry results saved.

In [ ]:
df.to_excel(
    RESULT_FILE,
    index=False
)

print("=" * 80)
print("FINAL QWEN FILE SAVED")
print("=" * 80)

print(
    RESULT_FILE
)

================================================================================
FINAL QWEN FILE SAVED
================================================================================
/content/drive/MyDrive/LLMValidation_LabeledIn/LabeledIn_Qwen3_8B_Results.xlsx